import Link from 'next/link';
import { ArrowRight, ArrowUpRight, ChartNoAxesCombined, Check, Compass, Layers3, Leaf, MoveUpRight, Target } from 'lucide-react';
import { PublicShell } from './chrome';

function WealthIllustration() {
  return <div className="public-hero-art" aria-label="Illustration of a sample financial overview">
    <div className="public-orbit" /><div className="public-orbit public-orbit-inner" /><div className="public-art-sun"><svg viewBox="0 0 70 70" aria-hidden="true"><path d="M35 0v70M0 35h70M10 10l50 50M10 60l50-50M20 3l30 64M3 20l64 30M3 50l64-30M20 67 50 3" stroke="currentColor" strokeWidth="2" /></svg></div>
    <div className="public-wealth-card"><div className="public-illustration-label">YOUR BIGGER PICTURE <span>DEMO</span></div><div className="public-wealth-number">₹24,86,500</div><div className="public-wealth-change"><MoveUpRight size={15} aria-hidden="true" /> A little progress, every month.</div><svg className="public-wealth-chart" viewBox="0 0 400 135" fill="none" aria-hidden="true"><path d="M0 20H400M0 65H400M0 110H400" stroke="#ffffff18" /><path d="M0 112C25 118 25 93 50 101S80 106 102 84S132 98 158 70S183 76 210 56S241 70 268 42S302 48 329 25S370 35 400 6" stroke="#d9ef83" strokeWidth="3" /><path d="M0 112C25 118 25 93 50 101S80 106 102 84S132 98 158 70S183 76 210 56S241 70 268 42S302 48 329 25S370 35 400 6V135H0Z" fill="#d9ef8313" /></svg><div className="public-wealth-footer"><span>One clear view</span><span>Fictional sample data</span></div></div>
    <div className="public-goal-note"><div className="public-goal-note-header"><span className="public-note-icon"><Target size={24} /></span><div><strong>A softer landing</strong><span>Peace of mind, in progress.</span></div></div><div className="public-art-progress"><i /></div><div className="public-note-caption"><span>₹2.5L saved</span><strong>42% there</strong></div></div>
    <span className="public-leaf-bubble"><Leaf size={28} aria-hidden="true" /></span>
  </div>;
}

export function MarketingHome() {
  return <PublicShell>
    <section className="public-hero public-container"><div className="public-hero-copy"><div className="public-eyebrow"><span className="public-mini-star">✳</span> YOUR MONEY, WITH PERSPECTIVE</div><h1>A clearer view.<br />A <em>richer life.</em></h1><p>Your everyday money and your bigger dreams, finally in the same picture. Understand where you are. Make room for what comes next.</p><div className="public-hero-actions"><Link href="/signup" className="public-button public-button-dark">Find your focus <ArrowUpRight size={19} /></Link><Link href="/demo" className="public-text-link">Take a look around <ArrowRight size={19} /></Link></div><div className="public-assurances"><span><Check size={16} /> Start with manual entries</span><span><Check size={16} /> Explore without an account</span></div></div><WealthIllustration /></section>
    <section className="public-value-strip public-container" aria-label="What WealthWise brings together"><p>Less scattered.<br />More considered.</p><div><Layers3 /><span><strong>Your whole picture</strong><small>Money, investments & goals</small></span></div><div><Target /><span><strong>A plan that feels yours</strong><small>Progress at your own pace</small></span></div><div><Compass /><span><strong>A little more confidence</strong><small>Clear tools & useful learning</small></span></div></section>
    <section className="public-section public-container"><div className="public-section-heading"><div><div className="public-eyebrow">THOUGHTFULLY CONNECTED</div><h2>Money has many parts.<br />Your picture shouldn’t.</h2></div><p>A calmer workspace for the decisions that shape your everyday life.</p></div><div className="public-feature-grid">
      <article className="public-feature"><span className="public-feature-index">01 / UNDERSTAND</span><h3>Know where<br />you stand.</h3><p>Bring accounts, transactions and holdings into one view. Give every number a little context.</p><div className="public-feature-mini"><span>MONTHLY CASH FLOW</span><strong>Room to breathe.</strong><div className="public-mini-bars">{[32, 56, 46, 75, 64, 90].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div></div><Link href="/product#understand" className="public-text-link">See the whole picture <ArrowUpRight size={17} /></Link></article>
      <article className="public-feature public-feature-warm"><span className="public-feature-index">02 / PLAN</span><h3>Make someday<br />a little closer.</h3><p>Give goals a target and spending a plan. Explore what regular saving could make possible.</p><div className="public-feature-mini public-feature-goal"><Target size={27} /><strong>A place of your own</strong><span>ONE CONTRIBUTION AT A TIME</span><div className="public-art-progress"><i /></div></div><Link href="/calculators" className="public-text-link">Explore a scenario <ArrowUpRight size={17} /></Link></article>
      <article className="public-feature public-feature-sage"><span className="public-feature-index">03 / GROW</span><h3>A wiser next step.<br />Then another.</h3><p>Understand the ideas behind your decisions. Learn with practical examples and a separate practice account.</p><div className="public-feature-mini public-feature-dark"><span>THE WEALTHWISE NOTEBOOK</span><strong>Small ideas.<br />Lasting perspective.</strong><span className="public-round-arrow"><ArrowUpRight /></span></div><Link href="/learn" className="public-text-link">Open the notebook <ArrowUpRight size={17} /></Link></article>
    </div></section>
    <section className="public-manifesto"><div className="public-container"><div className="public-eyebrow">A DIFFERENT KIND OF PROGRESS</div><div><h2>More peace of mind.<br />More room for living.<br /><em>That’s a richer life.</em></h2><p>Money is part of your life, not the whole of it. WealthWise gives you the perspective to make thoughtful choices, without the noise or the pressure to keep checking.</p></div></div></section>
    <section className="public-section public-container"><div className="public-section-heading"><div><div className="public-eyebrow">A SIMPLE PLACE TO START</div><h2>No perfect spreadsheet required.</h2></div></div><div className="public-how-grid">{[{ title: 'Start with what you know.', copy: 'Add a balance, a few transactions or your current holdings. You can build the picture gradually.' }, { title: 'Give your money a little direction.', copy: 'Set a monthly budget or name one goal. Use clear calculators to explore the possibilities.' }, { title: 'Come back with perspective.', copy: 'Review your progress, understand what changed, and make the next small adjustment.' }].map((step, index) => <article key={step.title}><span>0{index + 1}</span><h3>{step.title}</h3><p>{step.copy}</p></article>)}</div></section>
    <section className="public-learning-strip"><div className="public-container"><div><div className="public-eyebrow">FIVE MINUTES, A FRESH PERSPECTIVE</div><h2>A little learning<br />goes a long way.</h2><p>Compounding. Diversification. The real cost of a loan. Useful ideas, thoughtfully explained.</p><Link href="/learn" className="public-text-link">Explore the notebook <ArrowRight size={19} /></Link></div><Link href="/learn/compounding" className="public-article-preview"><div className="public-article-art"><ChartNoAxesCombined size={126} strokeWidth={1} /><span className="public-article-circle" /></div><div><span className="public-eyebrow">MONEY FOUNDATIONS · 5 MIN</span><h3>Small amounts.<br />A surprising future.</h3><span className="public-text-link">Understand compounding <ArrowUpRight size={18} /></span></div></Link></div></section>
    <section className="public-final-cta public-container"><div className="public-eyebrow">A CLEARER VIEW STARTS HERE</div><h2>Let’s make room<br />for <em>what matters.</em></h2><Link href="/signup" className="public-button public-button-dark">Create your workspace <ArrowUpRight size={19} /></Link><p>Prefer a look first? <Link href="/demo">Explore the sample workspace.</Link></p></section>
  </PublicShell>;
}
