import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { PublicShell } from './chrome';

type Section = { id?: string; title: string; paragraphs: string[]; bullets?: string[] };
const pages: Record<string, { eyebrow: string; title: string; introduction: string; sections: Section[] }> = {
  product: { eyebrow: 'THE WEALTHWISE WORKSPACE', title: 'One picture. A little more perspective.', introduction: 'Build an understanding of your finances with manual records, useful planning tools and a place to learn. Start small; add detail as you go.', sections: [
    { id: 'understand', title: 'Understand the money you already have.', paragraphs: ['Create cash, savings and retirement accounts. Record income, expenses and transfers, then review your cash flow for the month. Manual investment holdings and dated valuations bring your portfolio into the same picture.'], bullets: ['Accounts and activity with clear categories.', 'A portfolio view with allocation and purchase-cost gains.', 'A source date for manual valuations, with sample data clearly distinguished.'] },
    { title: 'Give your priorities a plan.', paragraphs: ['Set monthly category budgets and name your savings goals. Explore a regular contribution, loan repayment or target date using calculators whose assumptions you can see. Save useful scenarios and return to them later.'], bullets: ['Budgets grounded in your recorded spending.', 'Goals and saved SIP, EMI and target-saving scenarios.', 'Manual borrowing records and a clear separation between principal and interest.'] },
    { title: 'Learn without the pressure.', paragraphs: ['The notebook explains money concepts using small worked examples. A separate practice account lets you explore simulated orders with sample prices. Practice funds are never included in your personal net worth.'] },
    { title: 'Know where the numbers come from.', paragraphs: ['Your personal workspace uses the information you enter. The demo contains fictional sample records. Live bank connections, market prices and AI research are not connected; the application does not place real trades or move money.'] },
  ] },
  about: { eyebrow: 'OUR APPROACH', title: 'A calmer relationship with money.', introduction: 'WealthWise is built around a simple idea: understanding your money should leave more room for living.', sections: [
    { title: 'Clarity before complexity.', paragraphs: ['A useful financial picture connects everyday activity with longer-term goals. We bring those pieces into one workspace, with plain explanations and calculations that show their assumptions.'] },
    { title: 'Progress at your pace.', paragraphs: ['You do not need to import your whole financial history to begin. Add one account, record a few transactions or explore a calculator. The workspace becomes more useful as you give it more context.'] },
    { title: 'A thoughtful boundary.', paragraphs: ['WealthWise supports record keeping and education. It is not a bank, broker or investment adviser. It does not execute real trades, recommend specific securities or guarantee outcomes.'] },
  ] },
  security: { eyebrow: 'SECURITY & YOUR WORKSPACE', title: 'A clear source. A considered boundary.', introduction: 'Financial information deserves clear controls. Here is how the application separates personal records, sample data and future integrations.', sections: [
    { title: 'Your account and personal records.', paragraphs: ['Personal workspaces use Supabase authentication. Application requests verify the signed-in user, and database access policies restrict workspace records to their owner. Keep your sign-in details private and sign out on shared devices.'] },
    { title: 'Manual records; no bank credentials.', paragraphs: ['You can enter account names, balances and activity manually. WealthWise does not ask for bank passwords, card security codes, brokerage passwords or private keys. No bank connection or live trade execution is available in this release.'] },
    { title: 'Export and review your information.', paragraphs: ['Settings provides a downloadable workspace export and an activity CSV. Check files before importing and review the validation preview. Exports contain personal financial information; store them only where you intend.'] },
    { title: 'Report a problem.', paragraphs: ['If you notice an access problem or unexpected behaviour, use the project issue tracker linked from Help. Do not include passwords, access tokens, account numbers or financial exports in public reports. This page does not claim a security certification or independent audit.'] },
  ] },
  privacy: { eyebrow: 'PRIVACY', title: 'Know what goes into your workspace.', introduction: 'This page describes the data used by the current application. Updated 14 September 2026.', sections: [
    { title: 'Information you provide.', paragraphs: ['Your personal workspace can contain your display name, account names and balances, transactions, investment holdings, goals, budgets, debts, saved scenarios and learning progress. Enter only information you want to keep in the application. Bank credentials are not required.'] },
    { title: 'How that information is used.', paragraphs: ['Records are used to show your financial overview, calculate budgets and projections, and save your preferences. The application uses Supabase for authentication and workspace storage. Hosting requests are processed by the deployment provider. Authentication uses session cookies to keep you signed in.'] },
    { title: 'Sample data and imports.', paragraphs: ['The demo uses fictional records and is separate from your signed-in workspace. A CSV import is parsed for preview in your browser; accepted transaction records are saved only after you confirm the import. The interface explains validation errors before committing.'] },
    { title: 'Your controls.', paragraphs: ['You can update records and preferences, remove individual entries, export your workspace and sign out. Demo records can be reset separately. An export is a copy of your information; deleting a browser download does not delete the records in your account.'] },
    { title: 'External services and links.', paragraphs: ['No banking, brokerage or AI provider is connected to your workspace in this release. Links to outside websites have their own privacy practices. Do not place personal information in a public issue report. For questions about data handling, see the support options on the Help page.'] },
  ] },
  terms: { eyebrow: 'TERMS OF USE', title: 'A few clear expectations.', introduction: 'WealthWise is a personal-finance record-keeping and educational application. These terms describe the intended use of this release. Updated 14 September 2026.', sections: [
    { title: 'Use your own information responsibly.', paragraphs: ['Use an account you are authorized to access. Do not attempt to access another person’s workspace, interfere with the service or upload harmful content. You are responsible for the accuracy of manual records and for keeping your sign-in details private.'] },
    { title: 'Estimates are not guarantees.', paragraphs: ['Calculators use the assumptions you select. Future investment returns, interest rates, taxes, fees and inflation may differ. Educational content and rule-based observations are general information, not individualized financial, investment, tax or legal advice.'] },
    { title: 'Demo and practice data.', paragraphs: ['Demo holdings, sample markets and practice orders are fictional or illustrative. Practice execution uses sample prices and does not represent exchange execution. No real payment or trade is made through the application.'] },
    { title: 'Keep a copy of important records.', paragraphs: ['Check calculated results against original statements before making financial decisions. Use the export controls to keep a copy of records you need. Service availability and displayed information can be affected by errors, maintenance or network interruptions.'] },
    { title: 'Changes and support.', paragraphs: ['Features may change as the application develops. Review the current product and privacy pages when using a new feature. The Help page links to documentation and the project issue tracker; it does not promise a staffed or emergency support service.'] },
  ] },
  help: { eyebrow: 'A LITTLE HELP', title: 'Find your way. Keep your perspective.', introduction: 'Start with the essentials, or find the next step for a specific part of your workspace.', sections: [
    { title: 'Start with a manual account.', paragraphs: ['Create an account from your workspace and enter its current opening balance. Add income and expenses through Activity. Use the transfer action for money moving between your own accounts so it is not counted as new income or spending.'] },
    { title: 'Bring in a transaction file.', paragraphs: ['Settings includes a CSV template, validation preview and import confirmation. Dates use YYYY-MM-DD, amounts are in rupees, income is positive and spending is negative. An account ID must match an account in your workspace. Transfers should be entered through the transfer action.'] },
    { title: 'Understand your investment values.', paragraphs: ['Holdings use your entered quantity, average purchase cost and dated manual price. Simple gain is current value minus purchase cost; it is not an annualized return. Update valuations when you want a fresher view.'] },
    { title: 'Use goals and calculators together.', paragraphs: ['A goal records your target and progress. A calculator estimates what regular contributions or repayments could look like. Saved scenarios retain their inputs so you can revisit the same assumptions.'] },
    { title: 'Need to report an issue?', paragraphs: ['The project issue tracker is the current support channel. Include the page, steps to reproduce and the message you saw. Remove personal records, account identifiers, passwords and access tokens before submitting. There is no connected support chat or promised response time.'] },
  ] },
};

export function PublicPage({ slug }: { slug: string }) {
  const page = pages[slug];
  if (!page) return <PublicShell><section className="public-page-hero public-container"><div className="public-eyebrow">A DIFFERENT PATH</div><h1>This page isn’t here.</h1><p><Link href="/">Return to WealthWise</Link> or visit <Link href="/help">Help</Link>.</p></section></PublicShell>;
  return <PublicShell><div className="public-container"><header className="public-page-hero"><div className="public-eyebrow">{page.eyebrow}</div><h1>{page.title}</h1><p>{page.introduction}</p></header><div className="public-content-grid"><aside className="public-page-aside"><strong>WealthWise, in focus.</strong><p>Personal finance, thoughtfully connected.</p><Link href="/demo">Explore the demo</Link><Link href="/learn">Open the notebook</Link><Link href="/help">Find help</Link></aside><div className="public-prose">{page.sections.map(section => <section key={section.title} id={section.id}><h2>{section.title}</h2>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets.map(item => <li key={item}>{item}</li>)}</ul>}</section>)}{slug === 'help' && <div className="public-help-grid"><article className="public-help-card"><h3>Learn a useful idea.</h3><p>Short lessons, worked examples and a quick knowledge check.</p><Link href="/learn">Explore lessons <ArrowUpRight size={18} /></Link></article><article className="public-help-card"><h3>Report a product issue.</h3><p>Open the project’s issue tracker. Please keep personal financial information out of your report.</p><a href="https://github.com/sudo-anshul/wealth-wise/issues" target="_blank" rel="noreferrer">Open GitHub issues <ArrowUpRight size={18} /></a></article></div>}<div className="public-content-cta"><p><strong>Make the picture your own.</strong>Start with one account, one goal, or one useful idea.</p><Link href="/signup" className="public-button public-button-dark">Get started <ArrowUpRight size={18} /></Link></div></div></div></div></PublicShell>;
}
