import { describe,it,expect } from 'vitest';
import { createDemoWorkspace } from '@wealthwise/demo-data';
import { emptyWorkspace, workspaceSchema, holdingSchema } from '@wealthwise/contracts';
import { applyCommand, netWorth, portfolioValue, monthlyCashflow, accountBalance, calculateSIP, calculateEMI, practicePortfolio, toMinor, transactionsCSV } from './index';
const id='22222222-2222-4222-8222-222222222222';
describe('financial invariants',()=>{
  it('reconciles sample net worth without adding goal earmarks or practice funds',()=>{const s=createDemoWorkspace();expect(workspaceSchema.safeParse(s).success).toBe(true);expect(portfolioValue(s)).toBe(173650000);expect(netWorth(s)).toBe(248650000);});
  it('has a safe empty workspace',()=>{expect(netWorth(emptyWorkspace())).toBe(0);expect(monthlyCashflow(emptyWorkspace(),'2026-09').savingsMinor).toBe(0);});
  it('uses integer minor units with decimal rounding',()=>{expect(toMinor('0.105')).toBe(11);expect(toMinor('123.45')).toBe(12345);expect(()=>toMinor('Infinity')).toThrow();});
  it('conserves net worth and cash flow through a paired transfer',()=>{const s=createDemoWorkspace();const t=applyCommand(s,{type:'transfer',id,fromAccountId:s.accounts[0].id,toAccountId:s.accounts[1].id,amountMinor:100000,date:'2026-09-14',description:'Savings transfer'});expect(netWorth(t)).toBe(netWorth(s));expect(monthlyCashflow(t,'2026-09')).toEqual(monthlyCashflow(s,'2026-09'));expect(accountBalance(t,s.accounts[0].id)).toBe(accountBalance(s,s.accounts[0].id)-100000);const deleted=applyCommand(t,{type:'delete-transaction',id});expect(netWorth(deleted)).toBe(netWorth(s));expect(deleted.transactions).toEqual(s.transactions);});
  it('rejects orphaned and individual transfer edits',()=>{const s=createDemoWorkspace();expect(()=>applyCommand(s,{type:'delete-account',id:s.accounts[0].id})).toThrow();expect(()=>applyCommand(s,{type:'upsert-transaction',transaction:{...s.transactions[0],accountId:id}})).toThrow();expect(()=>applyCommand(s,{type:'upsert-transaction',transaction:{...s.transactions[0],category:'Transfer'}})).toThrow();});
  it('calculates zero-interest edge cases without division by zero',()=>{expect(calculateSIP(1000000,0,10)).toMatchObject({investedMinor:120000000,totalMinor:120000000,growthMinor:0});expect(calculateEMI(120000,0,12)).toEqual({monthlyMinor:10000,totalMinor:120000,interestMinor:0});});
  it('calculates EMI and end-of-month SIP with stated convention',()=>{expect(calculateEMI(50000000,9,60).monthlyMinor).toBe(1037918);expect(calculateSIP(1000000,12,1).totalMinor).toBe(12682503);});
  it('fills practice orders exactly once at trusted fixture prices',()=>{const s=createDemoWorkspace();const t=applyCommand(s,{type:'place-order',id,symbol:'NOVA',quantity:10,side:'buy'},'2026-09-14T12:00:00.000Z');expect(practicePortfolio(t).cashMinor).toBe(98750000);expect(practicePortfolio(t).holdings[0].quantity).toBe(10);expect(netWorth(t)).toBe(netWorth(s));expect(()=>applyCommand(t,{type:'place-order',id,symbol:'NOVA',quantity:10,side:'buy'})).toThrow(/already/);expect(()=>applyCommand(s,{type:'place-order',id,symbol:'NOVA',quantity:1000,side:'buy'})).toThrow(/cash/);expect(()=>applyCommand(s,{type:'place-order',id,symbol:'NOVA',quantity:10,side:'sell'})).toThrow(/own/);});
  it('does not mutate previous state on invalid import',()=>{const s=createDemoWorkspace();const length=s.transactions.length;expect(()=>applyCommand(s,{type:'import-transactions',transactions:[s.transactions[0]]})).toThrow(/Duplicate/);expect(s.transactions).toHaveLength(length);});
  it('neutralizes spreadsheet formula injection in exports',()=>{const s=createDemoWorkspace();s.transactions[0].description='=HYPERLINK("https://example.com")';expect(transactionsCSV(s)).toContain("\"'=HYPERLINK");});
  it('rejects positions and projections beyond safe numeric precision',()=>{const s=createDemoWorkspace();expect(holdingSchema.safeParse({...s.holdings[0],quantity:1000000,priceMinor:100000000000000}).success).toBe(false);expect(()=>calculateSIP(1000000000000,60,50)).toThrow(/precision/);});
});
