'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowRight,Sprout,ShieldCheck} from 'lucide-react';
import {useWorkspace} from '@/components/workspace-provider';
import {Button,Card,PageHeader,Field,Input,Select} from '@/components/ui';
import {toMinor} from '@wealthwise/domain';
import {accountSchema,preferencesSchema} from '@wealthwise/contracts';
export function OnboardingView(){const {ready}=useWorkspace();return ready?<OnboardingForm/>:<div className="notice" role="status">Preparing your workspace…</div>;}
function OnboardingForm(){const {state,mode,basePath,dispatch,pending}=useWorkspace();const router=useRouter();const [name,setName]=useState(state.preferences.name==='Your workspace'?'':state.preferences.name);const [account,setAccount]=useState('Everyday account');const [amount,setAmount]=useState('0');const [priority,setPriority]=useState('understand');const [error,setError]=useState('');const [step,setStep]=useState(1);
  async function finish(){setError('');try{const preferences=preferencesSchema.parse({...state.preferences,name:name.trim()});const firstAccount=state.accounts.length?null:accountSchema.parse({id:crypto.randomUUID(),name:account,type:'cash',openingBalanceMinor:toMinor(amount)});await dispatch({type:'save-preferences',preferences});if(firstAccount)await dispatch({type:'upsert-account',account:firstAccount});router.push(`${basePath}/${priority==='goals'?'goals':priority==='invest'?'portfolio':'overview'}`);}catch(e){setError(e instanceof Error?e.message:'Check your details and try again.');}}
  return <div style={{maxWidth:760,margin:'32px auto'}}><PageHeader eyebrow="A new beginning" title="Make room for your future." description="A little context now. A clearer picture ahead."/><Card><div className="row" style={{marginBottom:28}}><BadgeStep number={1} active={step===1}/><span>About you</span><ArrowRight size={16}/><BadgeStep number={2} active={step===2}/><span>Your first account</span></div><form className="form-stack" onSubmit={e=>{e.preventDefault();if(step===1){if(name.trim()){setError('');setStep(2);}else setError('Enter a display name, rather than only spaces.');}else void finish();}}>{step===1?<><Field label="What should we call you?"><Input autoComplete="given-name" required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Your first name"/></Field><Field label="Where would you like to begin?"><Select value={priority} onChange={e=>setPriority(e.target.value)}><option value="understand">Understand my money</option><option value="goals">Make progress toward a goal</option><option value="invest">See my investments clearly</option></Select></Field>{error&&<p role="alert" className="form-error">{error}</p>}<Button type="submit">A little more about your money <ArrowRight size={18}/></Button></>:<><div className="notice"><ShieldCheck size={22}/><span>{mode==='demo'?'The sample workspace is already set up. You can rename it and explore.':'Start with a manual balance. Bank connections can be added when providers become available.'}</span></div>{!state.accounts.length&&<><Field label="Account name"><Input value={account} onChange={e=>setAccount(e.target.value)} required maxLength={120}/></Field><Field label="Opening balance in ₹" hint="Enter the balance before the transactions you plan to add."><Input type="number" min={0} max={1000000000000} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></Field></>}{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><Button type="button" variant="secondary" disabled={pending} onClick={()=>setStep(1)}>Back</Button><Button type="submit" disabled={pending}>{pending?'Saving…':'Open my workspace'}<Sprout size={19}/></Button></div></>}</form></Card></div>;
}
function BadgeStep({number,active}:{number:number;active:boolean}){return <span style={{display:'inline-flex',alignItems:'center',justifyContent:'center',borderRadius:'50%',width:32,height:32,background:active?'var(--forest)':'var(--soft)',color:active?'var(--paper)':'var(--muted)',fontWeight:700}}>{number}</span>;}
