'use client';

import Link from 'next/link';
import { useEffect, useId, useMemo, useState } from 'react';
import { ArrowDownToLine, ArrowRight, ArrowUpRight, Bookmark, Calculator, Check, ChevronRight, Plus, Target, Trash2 } from 'lucide-react';
import { calculateEMI, calculateSIP, toMinor } from '@wealthwise/domain';
import { scenarioSchema, type Scenario } from '@wealthwise/contracts';
import { Badge, Button, Card, EmptyState, Field, Input, PageHeader, formatMoney } from '@/components/ui';
import { useWorkspace } from '@/components/workspace-provider';
import { PublicShell } from '@/features/public/chrome';
import { calculateGoalContribution } from './math';
import './planning.css';

type Kind = Scenario['kind'];
type Point = { year: number; valueMinor: number; investedMinor: number };
const labels: Record<Kind, string> = { sip: 'SIP & lump sum', emi: 'Loan EMI', goal: 'Goal savings' };

function ProjectionChart({ points }: { points: Point[] }) {
  const id = useId().replaceAll(':', '');
  const highest = Math.max(1, ...points.map(point => point.valueMinor));
  const lastYear = points.at(-1)?.year ?? 1;
  const position = (point: Point, key: 'valueMinor' | 'investedMinor') => `${52 + point.year / lastYear * 510},${178 - point[key] / highest * 146}`;
  const growthLine = points.map(point => position(point, 'valueMinor')).join(' ');
  const contributedLine = points.map(point => position(point, 'investedMinor')).join(' ');
  return <div className="planning-chart"><div className="planning-plot"><div className="planning-y-labels" aria-hidden="true"><span>{formatMoney(Math.round(highest), true)}</span><span>{formatMoney(Math.round(highest / 2), true)}</span><span>₹0</span></div><svg viewBox="52 25 518 160" preserveAspectRatio="none" role="img" aria-label={`Projected value and contributions over ${lastYear} ${lastYear === 1 ? 'year' : 'years'}. A data table follows the chart.`}><defs><linearGradient id={`projection-${id}`} x1="0" x2="0" y1="0" y2="1"><stop stopColor="#d9ef83" stopOpacity=".6" /><stop offset="1" stopColor="#d9ef83" stopOpacity=".08" /></linearGradient></defs>{[0, .5, 1].map(fraction => <line key={fraction} x1="52" x2="563" y1={178 - fraction * 146} y2={178 - fraction * 146} stroke="#dde3d4" vectorEffect="non-scaling-stroke" />)}<polygon points={`52,178 ${growthLine} 562,178`} fill={`url(#projection-${id})`} /><polyline points={growthLine} fill="none" stroke="#183b32" strokeWidth="3" vectorEffect="non-scaling-stroke" /><polyline points={contributedLine} fill="none" stroke="#6b8696" strokeWidth="2" strokeDasharray="6 5" vectorEffect="non-scaling-stroke" /></svg></div><div className="planning-x-labels" aria-hidden="true"><span>Today</span>{lastYear > 1 && <span>Year {Math.floor(lastYear / 2)}</span>}<span>Year {lastYear}</span></div><div className="planning-chart-legend"><span><i /> Estimated value</span><span><i /> Contributions</span></div><details className="planning-data-details"><summary>View the yearly data</summary><div className="planning-table-scroll" role="region" aria-label="Projection data" tabIndex={0}><table><thead><tr><th scope="col">Year</th><th scope="col">Contributed</th><th scope="col">Estimated value</th></tr></thead><tbody>{points.map(point => <tr key={point.year}><th scope="row">{point.year === 0 ? 'Today' : point.year}</th><td>{formatMoney(point.investedMinor)}</td><td>{formatMoney(point.valueMinor)}</td></tr>)}</tbody></table></div></details></div>;
}

export function CalculatorsView({ initialKind = 'sip', publicMode = false }: { initialKind?: Kind; publicMode?: boolean }) {
  const { state, mode, ready, pending, dispatch } = useWorkspace();
  const [kind, setKind] = useState<Kind>(initialKind);
  const [monthly, setMonthly] = useState('15000'); const [initial, setInitial] = useState('0'); const [principal, setPrincipal] = useState('2500000'); const [target, setTarget] = useState('2500000'); const [rate, setRate] = useState('8'); const [years, setYears] = useState('10');
  const [name, setName] = useState(''); const [activeId, setActiveId] = useState<string | null>(null); const [message, setMessage] = useState(''); const [saveError, setSaveError] = useState('');
  useEffect(() => { const params = new URLSearchParams(window.location.search); const requested = params.get('kind') ?? params.get('calculator'); if (requested === 'sip' || requested === 'emi' || requested === 'goal') setKind(requested); }, []);
  const calculation = useMemo(() => {
    try {
      if (!rate.trim() || !years.trim()) throw new Error('Enter a rate and a whole number of years.');
      const annualRate = Number(rate); const horizon = Number(years);
      if (!Number.isFinite(annualRate) || annualRate < 0 || annualRate > 60 || !Number.isInteger(horizon) || horizon < 1 || horizon > 50) throw new Error('Use a 0–60% annual rate and a whole-year horizon from 1 to 50.');
      if (kind === 'emi') { if (!principal.trim()) throw new Error('Enter the loan amount.'); const amount = toMinor(principal); if (amount <= 0) throw new Error('The loan amount must be greater than zero.'); const loan = calculateEMI(amount, annualRate, horizon * 12); return { kind, annualRate, horizon, principalMinor: amount, ...loan, investedMinor: amount, growthMinor: loan.interestMinor, points: [] as Point[], error: '' }; }
      if (kind === 'goal') { if (!target.trim()) throw new Error('Enter your target amount.'); const amount = toMinor(target); if (amount <= 0) throw new Error('The goal amount must be greater than zero.'); const monthlyMinor = calculateGoalContribution(amount, annualRate, horizon); const projection = calculateSIP(monthlyMinor, annualRate, horizon); return { kind, annualRate, horizon, principalMinor: amount, monthlyMinor, ...projection, error: '' }; }
      if (!monthly.trim() || !initial.trim()) throw new Error('Enter both contribution amounts; use 0 if there is no starting amount.');
      const monthlyMinor = toMinor(monthly); const initialMinor = toMinor(initial); if (monthlyMinor < 0 || initialMinor < 0) throw new Error('Contributions cannot be negative.'); if (monthlyMinor === 0 && initialMinor === 0) throw new Error('Add a monthly contribution or a starting amount to explore a projection.');
      const projection = calculateSIP(monthlyMinor, annualRate, horizon, initialMinor); return { kind, annualRate, horizon, principalMinor: initialMinor, monthlyMinor, ...projection, error: '' };
    } catch (error) { return { error: error instanceof Error ? error.message : 'Try smaller amounts or a shorter horizon.' }; }
  }, [kind, monthly, initial, principal, target, rate, years]);
  const valid = !calculation.error && 'totalMinor' in calculation;
  function changeKind(next: Kind) { setKind(next); setActiveId(null); setName(''); setMessage(''); setSaveError(''); }
  async function save() {
    if (!valid || !('annualRate' in calculation)) return;
    setMessage(''); setSaveError('');
    try { const scenario = scenarioSchema.parse({ id: activeId ?? crypto.randomUUID(), name: name.trim() || `${labels[kind]} · ${years} ${Number(years) === 1 ? 'year' : 'years'}`, kind, principalMinor: calculation.principalMinor, monthlyMinor: calculation.monthlyMinor, annualRate: calculation.annualRate, years: calculation.horizon }); await dispatch({ type: 'save-scenario', scenario }); setActiveId(scenario.id); setName(scenario.name); setMessage(mode === 'demo' ? 'Scenario saved in this browser’s demo workspace.' : 'Scenario saved to your workspace.'); } catch (error) { setSaveError(error instanceof Error ? error.message : 'Your scenario could not be saved.'); }
  }
  function load(scenario: Scenario) { setKind(scenario.kind); setRate(String(scenario.annualRate)); setYears(String(scenario.years)); setName(scenario.name); setActiveId(scenario.id); setMessage('Saved assumptions restored.'); setSaveError(''); if (scenario.kind === 'sip') { setInitial(String(scenario.principalMinor / 100)); setMonthly(String(scenario.monthlyMinor / 100)); } else if (scenario.kind === 'emi') setPrincipal(String(scenario.principalMinor / 100)); else setTarget(String(scenario.principalMinor / 100)); document.getElementById('planning-inputs')?.scrollIntoView({ behavior: 'auto', block: 'center' }); }
  async function remove(id: string) { setSaveError(''); try { await dispatch({ type: 'delete-scenario', id }); if (activeId === id) { setActiveId(null); setName(''); } setMessage('Saved scenario removed.'); } catch (error) { setSaveError(error instanceof Error ? error.message : 'Could not remove this scenario.'); } }
  function downloadProjection() {
    if (!valid || !('points' in calculation)) return;
    const rows = calculation.points.length ? ['year,contributions_inr,estimated_value_inr', ...calculation.points.map(point => `${point.year},${(point.investedMinor / 100).toFixed(2)},${(point.valueMinor / 100).toFixed(2)}`)] : ['principal_inr,annual_rate,months,monthly_emi_inr,total_interest_inr,total_repayment_inr', `${(calculation.principalMinor / 100).toFixed(2)},${rate},${Number(years) * 12},${(calculation.monthlyMinor / 100).toFixed(2)},${(calculation.growthMinor / 100).toFixed(2)},${(calculation.totalMinor / 100).toFixed(2)}`];
    const blob = new Blob([rows.join('\r\n')], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `wealthwise-${kind}-estimate.csv`; anchor.click(); URL.revokeObjectURL(url);
  }
  const content = <div className="planning-view"><PageHeader eyebrow="Room for possibility" title="Make the next step a little clearer." description="Change an assumption. Compare a possibility. Give your plan some perspective." />
    <div className="planning-tabs" role="group" aria-label="Choose calculator"><Button variant={kind === 'sip' ? 'primary' : 'secondary'} aria-pressed={kind === 'sip'} onClick={() => changeKind('sip')}><Calculator size={18} /> SIP & lump sum</Button><Button variant={kind === 'emi' ? 'primary' : 'secondary'} aria-pressed={kind === 'emi'} onClick={() => changeKind('emi')}>Loan EMI</Button><Button variant={kind === 'goal' ? 'primary' : 'secondary'} aria-pressed={kind === 'goal'} onClick={() => changeKind('goal')}><Target size={18} /> Goal savings</Button></div>
    <Card className="planning-calculator"><div className="planning-inputs" id="planning-inputs"><Badge tone="green">{kind === 'emi' ? 'FIXED-RATE ESTIMATE' : 'ILLUSTRATIVE PROJECTION'}</Badge><h2>{kind === 'sip' ? 'A little, regularly.' : kind === 'emi' ? 'See the whole repayment.' : 'Give someday a number.'}</h2><p>{kind === 'sip' ? 'Explore monthly contributions, a starting amount, or both.' : kind === 'emi' ? 'Balance the monthly payment with the total cost of a loan.' : 'Estimate the monthly contribution towards a future target, starting from zero.'}</p>
      <div className="planning-fields">{kind === 'sip' && <><Field label="Monthly contribution (₹)"><Input type="number" inputMode="decimal" min="0" max="1000000000" step="0.01" value={monthly} onChange={event => { setMonthly(event.target.value); setMessage(''); }} /></Field><Field label="Starting amount (₹)" hint="Use 0 for a regular contribution without a lump sum."><Input type="number" inputMode="decimal" min="0" max="1000000000" step="0.01" value={initial} onChange={event => { setInitial(event.target.value); setMessage(''); }} /></Field></>}{kind === 'emi' && <Field label="Loan amount (₹)"><Input type="number" inputMode="decimal" min="1" max="1000000000" step="0.01" value={principal} onChange={event => { setPrincipal(event.target.value); setMessage(''); }} /></Field>}{kind === 'goal' && <Field label="Target amount (₹)"><Input type="number" inputMode="decimal" min="1" max="1000000000" step="0.01" value={target} onChange={event => { setTarget(event.target.value); setMessage(''); }} /></Field>}
      <div className="planning-field-pair"><Field label={kind === 'emi' ? 'Annual interest (%)' : 'Assumed annual return (%)'}><Input type="number" inputMode="decimal" min="0" max="60" step="0.1" value={rate} onChange={event => { setRate(event.target.value); setMessage(''); }} /></Field><Field label={kind === 'emi' ? 'Loan term (years)' : 'Time horizon (years)'}><Input type="number" min="1" max="50" step="1" value={years} onChange={event => { setYears(event.target.value); setMessage(''); }} /></Field></div></div>
      <div className="planning-input-note"><span aria-hidden="true">↗</span><p>{kind === 'emi' ? 'A longer term can lower the EMI while increasing total interest.' : 'Try a lower return assumption too. Contributions are certain; investment returns are not.'}</p></div></div>
      <div className="planning-result" aria-live="polite">{valid && 'totalMinor' in calculation ? <><div className="planning-result-top"><span className="planning-result-label">{kind === 'emi' ? 'ESTIMATED MONTHLY EMI' : kind === 'goal' ? 'ESTIMATED MONTHLY CONTRIBUTION' : 'POTENTIAL FUTURE VALUE'}</span><Badge>ESTIMATE</Badge></div><div className="planning-total">{formatMoney(kind === 'sip' ? calculation.totalMinor : calculation.monthlyMinor)}</div><p className="planning-result-context">{kind === 'emi' ? `For ${Number(years) * 12} monthly payments` : kind === 'goal' ? `Towards ${formatMoney(calculation.principalMinor)} over ${years} ${Number(years) === 1 ? 'year' : 'years'}` : `After ${years} ${Number(years) === 1 ? 'year' : 'years'} at an assumed ${rate}% annual rate`}</p>
      <div className="planning-breakdown"><div><span>{kind === 'emi' ? 'Principal' : 'Total contributed'}</span><strong>{formatMoney(calculation.investedMinor)}</strong></div><div><span>{kind === 'emi' ? 'Total interest' : 'Assumed growth'}</span><strong>{formatMoney(calculation.growthMinor)}</strong></div>{kind === 'emi' && <div><span>Total repayment</span><strong>{formatMoney(calculation.totalMinor)}</strong></div>}</div>
      {calculation.points.length ? <ProjectionChart points={calculation.points} /> : <div className="planning-loan-visual"><div className="planning-loan-bar" role="img" aria-label={`Principal ${formatMoney(calculation.investedMinor)}, interest ${formatMoney(calculation.growthMinor)}`}><i style={{ width: `${calculation.investedMinor / calculation.totalMinor * 100}%` }} /><i style={{ width: `${calculation.growthMinor / calculation.totalMinor * 100}%` }} /></div><div className="planning-chart-legend"><span><i /> Principal</span><span><i /> Interest</span></div><p>Fixed rate, reducing balance and regular monthly payments. Fees, insurance, taxes and lender-specific rounding are excluded.</p></div>}
      <Button variant="ghost" onClick={downloadProjection}><ArrowDownToLine size={17} /> Download estimate</Button></> : <div className="planning-invalid"><Calculator size={38} aria-hidden="true" /><h3>A small adjustment will help.</h3><p role="alert">{calculation.error}</p><span>Try a smaller amount or a shorter horizon if the result exceeds the supported range.</span></div>}</div>
    </Card>
    <div className="planning-assumptions"><strong>The assumptions matter.</strong><p>{kind === 'emi' ? 'EMI uses a fixed annual rate divided by 12. The displayed instalment is rounded to the nearest paise; an actual final payment may differ. Verify a lender’s full schedule before a decision.' : 'Returns use the annual rate divided by 12 and contributions at the end of each month. The rate is constant for this illustration. Fees, taxes and inflation are excluded. Values are nominal; real markets do not grow in a smooth line.'}</p></div>
    <Card className="planning-save"><div><h2>{activeId ? 'Keep this scenario up to date.' : 'A possibility worth keeping?'}</h2><p>{mode === 'demo' ? 'Save assumptions in your browser’s demo workspace. No account is required.' : 'Save these assumptions to your personal workspace and revisit them later.'}</p></div><div className="planning-save-controls"><Field label="Scenario name"><Input value={name} onChange={event => setName(event.target.value)} placeholder={`${labels[kind]} · ${years} ${Number(years) === 1 ? 'year' : 'years'}`} maxLength={120} /></Field><Button disabled={!ready || pending || !valid} onClick={() => void save()}><Bookmark size={18} /> {pending ? 'Saving…' : activeId ? 'Update scenario' : 'Save scenario'}</Button>{activeId && <Button variant="ghost" onClick={() => { setActiveId(null); setName(''); setMessage('Ready to save a separate scenario.'); }}><Plus size={17} /> Save as new</Button>}</div>{message && <p className="planning-status" role="status"><Check size={17} /> {message}</p>}{saveError && <p className="planning-error" role="alert">{saveError}</p>}</Card>
    <div className="planning-saved-heading"><h2>Your saved possibilities.</h2><span>{state.scenarios.length} saved</span></div>{state.scenarios.length ? <div className="planning-scenario-grid">{state.scenarios.map(scenario => <Card key={scenario.id} className="planning-scenario"><Badge>{labels[scenario.kind]}</Badge><h3>{scenario.name}</h3><p>{scenario.years} {scenario.years === 1 ? 'year' : 'years'} · {scenario.annualRate}% annual assumption</p><div className="planning-scenario-amount"><span>{scenario.kind === 'emi' ? 'Loan amount' : scenario.kind === 'goal' ? 'Target' : 'Monthly contribution'}</span><strong>{formatMoney(scenario.kind === 'sip' ? scenario.monthlyMinor : scenario.principalMinor)}</strong></div><div className="planning-scenario-actions"><Button variant="ghost" onClick={() => load(scenario)}>Restore inputs <ChevronRight size={18} /></Button><button className="planning-delete" type="button" aria-label={`Delete scenario ${scenario.name}`} disabled={pending} onClick={() => void remove(scenario.id)}><Trash2 size={18} /></button></div></Card>)}</div> : <Card><EmptyState title="A little room for possibilities." description="Save a scenario above to keep its assumptions here." /></Card>}
    <div className="planning-learn-link"><div><span>MAKE THE NUMBERS MEAN SOMETHING</span><h3>{kind === 'emi' ? 'Understand the whole cost of borrowing.' : 'See what compounding can—and cannot—do.'}</h3></div><Link href={`/learn/${kind === 'emi' ? 'borrowing' : 'compounding'}`}>Read the short lesson <ArrowRight size={19} /></Link></div>
    {publicMode && <p className="planning-public-note">Exploring the public tools? Saved scenarios use the isolated demo in this browser. <Link href="/signup">Create an account</Link> for your personal workspace.</p>}
  </div>;
  return publicMode ? <PublicShell><div className="public-container planning-public">{content}</div></PublicShell> : content;
}
