'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,Download,Sparkles,BookOpen,ShieldCheck} from 'lucide-react';
import {useWorkspace} from '@/components/workspace-provider';
import {Button,Card,PageHeader,Metric,Badge,Field,Input,formatMoney} from '@/components/ui';
import {monthlyCashflow,categorySpending,accountBalance,calculateEMI,netWorth,portfolioValue} from '@wealthwise/domain';
import {financeToday} from '../finance/dates';
export function InsightsView(){
  const {state,mode,basePath}=useWorkspace();const [month,setMonth]=useState(mode==='demo'?'2026-09':financeToday().slice(0,7));
  const money=(value:number)=>state.preferences.hideBalances?'••••••':formatMoney(value);
  const cashflow=monthlyCashflow(state,month);const spending=categorySpending(state,month);const savingsRate=cashflow.incomeMinor?cashflow.savingsMinor/cashflow.incomeMinor*100:0;
  const liquid=state.accounts.filter(a=>a.type!=='retirement').reduce((s,a)=>s+accountBalance(state,a.id),0);const runway=cashflow.expenseMinor?Math.max(0,liquid)/cashflow.expenseMinor:null;
  const emis=state.debts.reduce((s,d)=>s+calculateEMI(d.balanceMinor,d.annualRate,d.remainingMonths).monthlyMinor,0);const overBudgets=state.budgets.filter(b=>b.month===month&&(spending[b.category]??0)>b.limitMinor);
  const notes=[
    {title:cashflow.incomeMinor?'Give your surplus a purpose.':'Start with a little context.',body:cashflow.incomeMinor?`You recorded ${money(cashflow.incomeMinor)} of income and ${money(cashflow.expenseMinor)} of expenses. ${cashflow.savingsMinor>=0?`${money(cashflow.savingsMinor)} is left before future commitments.`:'Recorded spending exceeded income this month.'}`:'Add income and expense records to see a meaningful monthly review.',href:'transactions',action:'Review activity'},
    {title:overBudgets.length?'A few plans need a second look.':'Make room for what matters.',body:!state.budgets.some(b=>b.month===month)?'No budgets are set for this month yet. Start with a few useful category limits, then compare them with your recorded spending.':overBudgets.length?`${overBudgets.map(b=>b.category).join(', ')} ${overBudgets.length===1?'is':'are'} above the current monthly limit. Review the entries or adjust the plan to reflect reality.`:'Your recorded spending is within the budgets you have set. A plan is useful when it fits your real life.',href:'budgets',action:'Review budgets'},
    {title:'See your borrowing in context.',body:state.debts.length?`Your remaining loans have an estimated combined EMI of ${money(emis)}. This estimate assumes constant rates and excludes fees and lender-specific rounding.`:'No loans have been added. Add a remaining balance and term when you want to explore repayment scenarios.',href:'debt',action:'Explore borrowing'},
    {title:'Keep goals connected to reality.',body:state.goals.length?`${state.goals.length} goals are recorded, with ${state.goals.filter(goal=>goal.savedMinor<goal.targetMinor).length} still in progress. Earmarked savings are planning allocations, so they do not increase net worth or automatically move money.`:'A first goal can turn a distant idea into a monthly habit. Set a target, a timeline, and a contribution you can sustain.',href:'goals',action:'Visit your goals'}
  ];
  function exportReport(){const report={title:'WealthWise monthly review',period:month,source:mode==='demo'?'fictional sample':'manual entries',generatedAt:new Date().toISOString(),currency:'INR',amountUnit:'paise',currentNetWorthMinor:netWorth(state),currentPortfolioValueMinor:portfolioValue(state),valuationBasis:'Current recorded balances and prices, not historical valuations',cashflow,categorySpending:spending,estimatedMonthlyDebtPaymentMinor:emis,notes:notes.map(n=>({title:n.title,detail:n.body})),assumptions:'Based only on recorded entries; no connected financial or AI providers. Projections exclude fees and taxes.'};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`wealthwise-review-${month}.json`;a.click();URL.revokeObjectURL(url);}
  return <div className="stack"><PageHeader eyebrow="A little clarity, every month" title="Your money, in perspective." description="A useful review of the numbers you have recorded, with clear reasons behind every observation." action={<Button variant="secondary" onClick={exportReport}><Download size={18}/>Export review</Button>}/><div className="between"><Badge tone="green"><Sparkles size={14}/>Calculated from your records</Badge><Field label="Review month"><Input aria-label="Review month" type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></Field></div><div className="grid-3"><Metric label="Monthly surplus" value={money(cashflow.savingsMinor)} detail="Recorded income less recorded spending"/><Metric label="Recorded savings rate" value={cashflow.incomeMinor?`${savingsRate.toFixed(1)}%`:'—'} detail="Surplus divided by recorded income"/><Metric label="Cash cushion" value={runway!==null?`${runway.toFixed(1)} months`:'—'} detail={liquid<0?"Recorded cash and savings are below zero; review your account balances":"Current cash and savings divided by this month’s recorded expenses"}/></div><div className="notice"><ShieldCheck size={22}/><span>These observations use deterministic calculations. Incomplete records affect the result. The AI research provider is not connected, and no automatic investment recommendations are generated.</span></div><div className="grid-2">{notes.map((n,i)=><Card key={n.title}><p className="eyebrow" style={{marginBottom:20}}>0{i+1} · Your next step</p><h2 style={{fontFamily:'var(--serif)',fontWeight:400,fontSize:32,marginBottom:16}}>{n.title}</h2><p style={{lineHeight:1.8}}>{n.body}</p><Link href={`${basePath}/${n.href}`} className="text-link" style={{marginTop:24}}>{n.action}<ArrowUpRight size={18}/></Link></Card>)}</div><Card><div className="between"><div><p className="eyebrow" style={{marginBottom:10}}>A thought to take with you</p><h2>Confidence grows with understanding.</h2><p style={{marginTop:12}}>A five-minute lesson can make your next decision a little clearer.</p></div><Link href={`${basePath}/learn`} className="button button-primary"><BookOpen size={18}/>Open the notebook</Link></div></Card></div>;
}
