'use client';
import type { ReactNode, ButtonHTMLAttributes, InputHTMLAttributes, SelectHTMLAttributes } from 'react';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import { X, Sprout } from 'lucide-react';
import clsx from 'clsx';
export function Button({variant='primary',className,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'lime'|'ghost'}){return <button className={clsx('button',`button-${variant}`,className)} {...props}>{children}</button>;}
export function Input({className,...props}:InputHTMLAttributes<HTMLInputElement>){return <input className={clsx('input',className)} {...props}/>;}
export function Select({className,...props}:SelectHTMLAttributes<HTMLSelectElement>){return <select className={clsx('input',className)} {...props}/>;}
export function Card({children,className}:{children:ReactNode;className?:string}){return <section className={clsx('card',className)}>{children}</section>;}
export function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:ReactNode;action?:ReactNode}){return <header className="page-header"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<div className="page-description">{description}</div>}</div>{action&&<div className="page-actions">{action}</div>}</header>;}
export function Metric({label,value,detail}:{label:string;value:ReactNode;detail?:ReactNode}){return <Card className="metric"><p className="metric-label">{label}</p><div className="metric-value money">{value}</div>{detail&&<div className="metric-detail">{detail}</div>}</Card>;}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'green'|'coral'}){return <span className={`badge badge-${tone}`}>{children}</span>;}
export function EmptyState({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="empty-state"><Sprout aria-hidden size={32}/><h2>{title}</h2><p>{description}</p>{action}</div>;}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function Dialog({open,onOpenChange,title,description,children}:{open:boolean;onOpenChange:(open:boolean)=>void;title:string;description?:string;children:ReactNode}){return <DialogPrimitive.Root open={open} onOpenChange={onOpenChange}><DialogPrimitive.Portal><DialogPrimitive.Overlay className="dialog-overlay"/><DialogPrimitive.Content className="dialog-content" aria-describedby={description?undefined:undefined}><div className="dialog-heading"><div><DialogPrimitive.Title>{title}</DialogPrimitive.Title>{description?<DialogPrimitive.Description>{description}</DialogPrimitive.Description>:<DialogPrimitive.Description className="sr-only">Review the details below.</DialogPrimitive.Description>}</div><DialogPrimitive.Close className="icon-button" aria-label="Close dialog"><X size={22}/></DialogPrimitive.Close></div>{children}</DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>;}
export function formatMoney(minor:number,compact=false){if(compact&&Math.abs(minor)>=10000000)return `₹${(minor/10000000).toLocaleString('en-IN',{maximumFractionDigits:2})}L`;return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:0,maximumFractionDigits:minor%100?2:0}).format(minor/100);}
