'use client';

import { useEffect, useMemo, useState, type ReactNode } from 'react';
import Link from 'next/link';
import { ArrowDownLeft, ArrowRight, ArrowUpRight, ArrowLeftRight, BookOpen, CalendarDays, CheckCheck, CircleHelp, Download, HeartPulse, Home, Info, Landmark, Leaf, Pencil, PiggyBank, Plane, Plus, Search, ShieldCheck, ShoppingBag, Sparkles, Star, Wallet } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Debt, Goal, Holding, Transaction, Workspace } from '@wealthwise/contracts';
import { accountBalance, calculateEMI, categorySpending, holdingCost, holdingValue, instruments, monthlyCashflow, netWorth, portfolioValue } from '@wealthwise/domain';
import { useWorkspace } from '@/components/workspace-provider';
import { Badge, Button, Dialog, EmptyState, Metric, PageHeader, formatMoney } from '@/components/ui';
import { FinanceEditor, type EditorState } from './finance-editor';
import { downloadCsv, downloadText } from './export';
import { exportTransactionsCSV } from '@/lib/transactions-csv';
import { financeToday } from './dates';
import './finance.css';

const COLORS = ['#284c3c', '#a9bf78', '#d7b999', '#8fa99a', '#d68a71'];
const currentMonth = () => financeToday().slice(0, 7);
const dateLabel = (date: string, long = false) => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: long ? 'long' : 'short', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${date}T12:00:00Z`));
const monthLabel = (month: string) => new Intl.DateTimeFormat('en-IN', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${month}-01T12:00:00Z`));
const percent = (part: number, total: number) => total > 0 ? part / total * 100 : 0;
const shortNumber = (value: number) => new Intl.NumberFormat('en-IN', { maximumFractionDigits: 6 }).format(value);
type Edit = (editor: EditorState) => void;
type CatalogInstrument = typeof instruments[number];

function useFinance() {
  const context = useWorkspace();
  const money = (value: number, compact = false) => context.state.preferences.hideBalances ? '••••••' : formatMoney(value, compact);
  const href = (view: string) => `${context.basePath}/${view}`;
  return { ...context, money, href };
}

function SectionHead({ title, description, action }: { title: string; description?: string; action?: ReactNode }) {
  return <div className="fin-card-head"><div><h2>{title}</h2>{description && <p>{description}</p>}</div>{action}</div>;
}

function TextLink({ children, view }: { children: ReactNode; view: string }) {
  const { href } = useFinance();
  return <Link className="fin-link" href={href(view)}>{children}<ArrowRight size={17}/></Link>;
}

function SourceNote({ manual = false }: { manual?: boolean }) {
  const { mode } = useFinance();
  return <span className="fin-muted">{mode === 'demo' ? 'Fictional sample data' : manual ? 'Manually recorded values' : 'Your recorded data'}</span>;
}

function MetricRow({ items }: { items: { label: string; value: string; detail: string }[] }) {
  return <div className="fin-grid fin-grid-3">{items.map(item => <div className="fin-metric" key={item.label}><Metric label={item.label} value={item.value} detail={item.detail}/></div>)}</div>;
}

function Progress({ value, tone = 'forest', label }: { value: number; tone?: string; label: string }) {
  return <div className="fin-progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100, Math.max(0, Number(value.toFixed(1))))} aria-label={label}><span className={tone} style={{ width: `${Math.min(100, Math.max(0, value))}%` }}/></div>;
}

function CategoryIcon({ category, size = 19 }: { category: string; size?: number }) {
  if (category === 'Housing' || category === 'Utilities') return <Home size={size}/>;
  if (category === 'Health') return <HeartPulse size={size}/>;
  if (category === 'Salary' || category === 'Other income') return <Landmark size={size}/>;
  if (category === 'Transfer') return <ArrowLeftRight size={size}/>;
  if (category === 'Learning') return <BookOpen size={size}/>;
  if (category === 'Food' || category === 'Shopping') return <ShoppingBag size={size}/>;
  return <Wallet size={size}/>;
}

function getAssetMix(state: Workspace) {
  const classes = new Map<string, number>();
  state.holdings.forEach(h => classes.set(h.assetClass, (classes.get(h.assetClass) ?? 0) + holdingValue(h)));
  return [...classes.entries()].map(([name, valueMinor], index) => ({ name, valueMinor, color: COLORS[index % COLORS.length] }));
}

function AllocationCard() {
  const { state, money, mode } = useFinance();
  const mix = getAssetMix(state);
  const total = portfolioValue(state);
  return <section className="fin-card">
    <SectionHead title="A thoughtful mix" action={<TextLink view="portfolio">Your holdings</TextLink>}/>
    {total > 0 ? <>
      <div className="fin-allocation"><div className="fin-donut" role="img" aria-label={`Asset allocation: ${mix.map(m => `${m.name} ${percent(m.valueMinor, total).toFixed(1)}%`).join(', ')}`}>
        <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={mix} dataKey="valueMinor" nameKey="name" innerRadius="70%" outerRadius="94%" paddingAngle={3} startAngle={90} endAngle={-270} stroke="none" isAnimationActive={false}>{mix.map(m => <Cell key={m.name} fill={m.color}/>)}</Pie></PieChart></ResponsiveContainer>
        <div className="fin-donut-center"><span>Invested assets</span><b>{money(total, true)}</b></div>
      </div><div className="fin-legend">{mix.map(m => <div className="fin-legend-row" key={m.name}><span className="fin-dot" style={{ background: m.color }}/><span>{m.name}</span><strong>{percent(m.valueMinor, total).toFixed(1)}%</strong></div>)}</div></div>
      <div className="fin-footnote">{state.holdings.length} {mode === 'demo' ? 'sample' : 'recorded'} holdings. Allocation uses each holding’s recorded asset class; underlying fund exposure may differ. Cash and retirement accounts are separate.</div>
    </> : <EmptyState title="Your mix starts here." description="Add an investment to see how your holdings fit together." action={<TextLink view="portfolio">Add your first holding</TextLink>}/>}
  </section>;
}

function GoalMinis() {
  const { state, money, href } = useFinance();
  return <section className="fin-card"><SectionHead title="Life, in the making" action={<TextLink view="goals">All goals</TextLink>}/>
    {state.goals.slice(0, 3).map((goal, i) => <Link href={href('goals')} key={goal.id} className="fin-goal-mini"><div className={`fin-icon-tile ${goal.color === 'coral' ? 'coral' : ''}`}>{i === 0 ? <Home size={22}/> : i === 1 ? <Plane size={22}/> : <ShieldCheck size={22}/>}</div><div><div className="fin-between"><h3>{goal.name}</h3><span>{percent(goal.savedMinor, goal.targetMinor).toFixed(0)}%</span></div><Progress value={percent(goal.savedMinor, goal.targetMinor)} tone={goal.color} label={`${goal.name} progress`}/><div className="fin-ledger-sub">{money(goal.savedMinor)} of {money(goal.targetMinor)}</div></div></Link>)}
    {!state.goals.length && <EmptyState title="What comes next?" description="Give something meaningful a savings goal." action={<TextLink view="goals">Create a goal</TextLink>}/>}
  </section>;
}

function TransactionTable({ rows, edit, compact = false }: { rows: Transaction[]; edit: Edit; compact?: boolean }) {
  const { state, money } = useFinance();
  return <div className="fin-table-wrap" tabIndex={0} role="region" aria-label="Transaction records"><table className="fin-table"><thead><tr><th>Transaction</th><th className="fin-hide-mobile">Category</th>{!compact && <th className="fin-hide-mobile">Account</th>}<th>Date</th><th className="right">Amount</th>{!compact && <th><span className="sr-only">Actions</span></th>}</tr></thead><tbody>
    {rows.map(transaction => <tr key={transaction.id}><td><div className="fin-table-name"><span className={`fin-icon-tile ${transaction.amountMinor < 0 ? 'coral' : ''}`}><CategoryIcon category={transaction.category} size={18}/></span><div><strong>{transaction.description}</strong>{transaction.transferId && <small>Paired transfer · excluded from cash flow</small>}</div></div></td><td className="fin-hide-mobile"><Badge tone="neutral">{transaction.category}</Badge></td>{!compact && <td className="fin-hide-mobile">{state.accounts.find(a => a.id === transaction.accountId)?.name ?? 'Account unavailable'}</td>}<td>{dateLabel(transaction.date)}</td><td className={`right amount ${transaction.amountMinor > 0 && !transaction.transferId ? 'fin-positive' : ''}`}>{transaction.amountMinor < 0 ? '−' : '+'}{money(Math.abs(transaction.amountMinor))}</td>{!compact && <td><div className="fin-row-actions"><button type="button" className="fin-icon-button" aria-label={`Edit ${transaction.description}`} onClick={() => edit({ kind: 'transaction', entity: transaction })}><Pencil size={17}/></button></div></td>}</tr>)}
    {!rows.length && <tr><td colSpan={compact ? 4 : 6}><div className="fin-empty-inline">No entries match this view. Try a different period or filter.</div></td></tr>}
  </tbody></table></div>;
}

function Overview({ edit, month, onMonth }: { edit: Edit; month: string; onMonth: (month: string) => void }) {
  const { state, mode, money, href } = useFinance();
  const [breakdown, setBreakdown] = useState(false);
  const cashflow = monthlyCashflow(state, month);
  const cash = state.accounts.filter(a => a.type !== 'retirement').reduce((sum, a) => sum + accountBalance(state, a.id), 0);
  const retirement = state.accounts.filter(a => a.type === 'retirement').reduce((sum, a) => sum + accountBalance(state, a.id), 0);
  const invested = portfolioValue(state);
  const liabilities = state.debts.reduce((sum, d) => sum + d.balanceMinor, 0);
  const worth = netWorth(state);
  const assets = worth + liabilities;
  const assetBars = [{ name: 'Investments', amount: invested }, { name: 'Cash & savings', amount: cash }, { name: 'Retirement', amount: retirement }];
  const recent = [...state.transactions].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 4);
  const cashBars = [{ name: 'Money in', amount: cashflow.incomeMinor, fill: '#284c3c' }, { name: 'Money out', amount: cashflow.expenseMinor, fill: '#d68a71' }];
  return <>
    <PageHeader eyebrow="Your financial workspace" title="Your bigger picture." description="A little clarity for today. A little confidence for tomorrow." action={<Button onClick={() => edit(state.accounts.length ? { kind: 'transaction' } : { kind: 'account' })}><Plus size={18}/>Add an entry</Button>}/>
    <div className="fin-grid fin-main-grid fin-hero-grid">
      <section className="fin-card fin-hero-card">
        <div className="fin-between"><span className="fin-kicker">Your net worth</span><Badge tone="green">{mode === 'demo' ? 'Sample workspace' : 'Manual records'}</Badge></div>
        <div className="fin-net-value">{money(worth)}</div><span className="fin-muted">Your assets, less what you owe.</span>
        {assets > 0 ? <div className="fin-chart compact" role="img" aria-label={`Current asset values: ${assetBars.map(b => `${b.name} ${money(b.amount)}`).join(', ')}`}><ResponsiveContainer width="100%" height="100%"><BarChart data={assetBars} layout="vertical" margin={{ left: 0, right: 12, top: 4, bottom: 2 }}><XAxis type="number" hide/><YAxis dataKey="name" type="category" axisLine={false} tickLine={false} width={114} tick={{ fill: '#c8d8bd', fontSize: 14 }}/><Tooltip cursor={{ fill: '#ffffff0a' }} formatter={v => money(Number(v))}/><Bar dataKey="amount" name="Current recorded value" fill="#d9ef83" radius={[0, 5, 5, 0]} barSize={15} isAnimationActive={false}/></BarChart></ResponsiveContainer></div> : <div className="fin-chart-empty"><Leaf size={32}/><p>A clear picture starts with one account. Your totals will grow as you add your records.</p></div>}
        <div className="fin-hero-foot"><div><span>Total assets</span><strong>{money(assets)}</strong></div><div><span>Total liabilities</span><strong>{money(liabilities)}</strong></div></div>
        <button className="fin-link" onClick={() => setBreakdown(true)} style={{ marginTop: 15 }}>How the pieces add up<ArrowRight size={17}/></button>
      </section>
      <section className="fin-card"><SectionHead title="A month in motion" action={<label className="fin-month-label"><CalendarDays size={17}/><input type="month" value={month} onChange={e => e.target.value && onMonth(e.target.value)} aria-label="Cash-flow month"/></label>}/><div className="fin-inout"><div><span><ArrowDownLeft size={16}/>Money in</span><strong>{money(cashflow.incomeMinor)}</strong></div><div><span><ArrowUpRight size={16}/>Money out</span><strong>{money(cashflow.expenseMinor)}</strong></div></div>
        <div className="fin-chart compact fin-cashflow-chart" role="img" aria-label={`${monthLabel(month)}: income ${money(cashflow.incomeMinor)}, spending ${money(cashflow.expenseMinor)}`}><ResponsiveContainer width="100%" height="100%"><BarChart data={cashBars} margin={{ left: 0, right: 0, top: 10, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e7edda"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#748668', fontSize: 14 }}/><YAxis hide/><Tooltip cursor={{ fill: '#f0f4e7' }} formatter={v => money(Number(v))}/><Bar dataKey="amount" name="Recorded amount" radius={[6, 6, 0, 0]} maxBarSize={60} isAnimationActive={false}>{cashBars.map(b => <Cell key={b.name} fill={b.fill}/>)}</Bar></BarChart></ResponsiveContainer></div>
        <div className="fin-savings fin-between"><div><span className="fin-muted">{cashflow.savingsMinor >= 0 ? 'Room to grow' : 'Spending above income'}</span><strong>{money(Math.abs(cashflow.savingsMinor))}</strong><span className="fin-muted">{cashflow.savingsMinor >= 0 ? 'Income less recorded spending' : 'Recorded spending less income'}</span></div><div className="fin-percent">{cashflow.incomeMinor > 0 ? `${percent(cashflow.savingsMinor, cashflow.incomeMinor).toFixed(0)}%` : '—'}</div></div>
      </section>
    </div>
    <MetricRow items={[{ label: 'Invested for tomorrow', value: money(invested), detail: `${state.holdings.length} ${mode === 'demo' ? 'sample' : 'recorded'} holdings` }, { label: 'Ready when you need it', value: money(cash), detail: 'Cash and savings; retirement kept separate' }, { label: 'Dreams taking shape', value: `${state.goals.length} ${state.goals.length === 1 ? 'goal' : 'goals'}`, detail: 'Earmarked savings are already part of your assets' }]}/>
    <div className="fin-grid fin-grid-2"><AllocationCard/><GoalMinis/></div>
    <div className="fin-notice"><Sparkles size={22}/><p><strong>Your picture is only as complete as your records.</strong><br/>{mode === 'demo' ? 'Try changing a budget or adding a goal. Every screen updates from the same fictional workspace.' : 'Keep balances and valuation dates current, and record transfers as paired movements between accounts.'}</p><TextLink view="accounts">Review accounts</TextLink></div>
    <section className="fin-card fin-table-card"><SectionHead title="The latest little things" action={<TextLink view="transactions">All activity</TextLink>}/><TransactionTable rows={recent} edit={edit} compact/>{!state.transactions.length && <div style={{ padding: '0 28px 24px' }}><Button variant="secondary" onClick={() => edit(state.accounts.length ? { kind: 'transaction' } : { kind: 'account' })}>Start with an entry<Plus size={17}/></Button></div>}</section>
    <Dialog open={breakdown} onOpenChange={setBreakdown} title="All the pieces, together." description="Every number has a place in your financial picture."><div className="finance-dialog"><div className="fin-detail-list"><div><span>Investment holdings</span><strong>{money(invested)}</strong></div><div><span>Cash & savings</span><strong>{money(cash)}</strong></div><div><span>Retirement / EPF</span><strong>{money(retirement)}</strong></div><div><span>Total assets</span><strong>{money(assets)}</strong></div><div><span>Outstanding loans</span><strong>− {money(liabilities)}</strong></div><div><span>Net worth</span><strong>{money(worth)}</strong></div></div><p className="fin-dialog-copy">Account balances come from opening balances and transactions. Holdings use the last price you recorded. Goals earmark existing money, and practice funds stay out of your net worth.</p><div className="fin-form-actions"><Link className="fin-link" href={href('accounts')} onClick={() => setBreakdown(false)}>Review your accounts<ArrowRight size={17}/></Link><Button variant="secondary" onClick={() => setBreakdown(false)}>Done</Button></div></div></Dialog>
  </>;
}

function Accounts({ edit }: { edit: Edit }) {
  const { state, money, href, mode } = useFinance();
  const total = state.accounts.reduce((sum, a) => sum + accountBalance(state, a.id), 0);
  const retirement = state.accounts.filter(a => a.type === 'retirement').reduce((sum, a) => sum + accountBalance(state, a.id), 0);
  return <><PageHeader eyebrow="Your money, together" title="A place for every piece." description="Cash, savings, and retirement. Bring your everyday picture into focus." action={<Button onClick={() => edit({ kind: 'account' })}><Plus size={18}/>Add account</Button>}/>
    {state.accounts.length ? <>
      <MetricRow items={[{ label: 'All account balances', value: money(total), detail: `${state.accounts.length} manually tracked accounts` }, { label: 'Cash & savings', value: money(total - retirement), detail: 'Everyday money and cash reserves' }, { label: 'Retirement / EPF', value: money(retirement), detail: 'Long-term accounts shown separately' }]}/>
      <div className="fin-grid fin-grid-3">{state.accounts.map(account => { const count = state.transactions.filter(t => t.accountId === account.id).length; return <section className="fin-card fin-account-card" key={account.id}><div className="fin-card-head"><div className="fin-icon-tile">{account.type === 'retirement' ? <Leaf size={23}/> : account.type === 'savings' ? <PiggyBank size={23}/> : <Landmark size={23}/>}</div><button className="fin-icon-button" onClick={() => edit({ kind: 'account', entity: account })} aria-label={`Edit ${account.name}`}><Pencil size={18}/></button></div><h2 className="fin-account-name">{account.name}</h2><Badge tone="neutral">{account.type === 'retirement' ? 'Retirement / EPF' : account.type === 'savings' ? 'Savings' : 'Everyday account'}</Badge><div className="fin-account-value fin-number">{money(accountBalance(state, account.id))}</div><SourceNote manual/><div className="fin-account-meta"><span>{count} recorded {count === 1 ? 'entry' : 'entries'}</span><Link className="fin-link" href={`${href('transactions')}?account=${account.id}`}>View activity<ArrowRight size={16}/></Link></div><div className="fin-form-actions" style={{ justifyContent: 'flex-start', paddingTop: 17 }}><Button variant="secondary" onClick={() => edit({ kind: 'transaction', accountId: account.id })}><Plus size={17}/>Add entry</Button></div></section>; })}</div>
      <div className="fin-notice info"><ArrowLeftRight size={22}/><p><strong>Moving money between your accounts?</strong><br/>A transfer creates two linked entries and leaves income and spending unchanged.</p><Button variant="secondary" disabled={state.accounts.length < 2} onClick={() => edit({ kind: 'transfer' })}>Record transfer</Button></div>
    </> : <EmptyState title="Start with one familiar account." description="Give an account a name and an opening balance. You can add transactions when you are ready." action={<Button onClick={() => edit({ kind: 'account' })}><Plus size={18}/>Add your first account</Button>}/>}
    <div className="fin-notice info"><ShieldCheck size={21}/><p>{mode === 'demo' ? 'These are fictional accounts in a browser-saved demo. ' : 'These accounts contain manually recorded balances. '}No bank connection is active. Never enter banking passwords or full account numbers.</p></div>
  </>;
}

function Transactions({ edit, month, onMonth }: { edit: Edit; month: string; onMonth: (month: string) => void }) {
  const { state, money, mode } = useFinance();
  const [search, setSearch] = useState('');
  const [accountFilter, setAccountFilter] = useState('all');
  const [typeFilter, setTypeFilter] = useState('all');
  const [categoryFilter, setCategoryFilter] = useState('all');
  const [allMonths, setAllMonths] = useState(false);
  useEffect(() => { const account = new URLSearchParams(window.location.search).get('account'); if (account) setAccountFilter(account); }, []);
  const cashflow = monthlyCashflow(state, month);
  const rows = useMemo(() => state.transactions.filter(transaction => {
    const matchesType = typeFilter === 'all' || (typeFilter === 'transfer' ? Boolean(transaction.transferId) : typeFilter === 'income' ? transaction.amountMinor > 0 && !transaction.transferId : transaction.amountMinor < 0 && !transaction.transferId);
    return (allMonths || transaction.date.startsWith(month)) && matchesType && (accountFilter === 'all' || transaction.accountId === accountFilter) && (categoryFilter === 'all' || transaction.category === categoryFilter) && `${transaction.description} ${transaction.category}`.toLowerCase().includes(search.toLowerCase());
  }).sort((a, b) => b.date.localeCompare(a.date)), [state.transactions, month, search, accountFilter, typeFilter, categoryFilter, allMonths]);
  const exportRows = () => downloadText('wealthwise-transactions.csv', exportTransactionsCSV(rows, state.accounts));
  return <><PageHeader eyebrow="The everyday details" title="Every little thing, together." description="A clear record of what came in, where it went, and what moved between accounts." action={<div className="fin-row"><Button variant="secondary" onClick={exportRows} disabled={!rows.length}><Download size={18}/>Export</Button><Button onClick={() => edit(state.accounts.length ? { kind: 'transaction' } : { kind: 'account' })}><Plus size={18}/>Add entry</Button></div>}/>
    <MetricRow items={[{ label: `Money in · ${monthLabel(month)}`, value: money(cashflow.incomeMinor), detail: 'Income entries; transfers excluded' }, { label: 'Money out', value: money(cashflow.expenseMinor), detail: 'Spending entries; transfers excluded' }, { label: 'Net cash flow', value: money(cashflow.savingsMinor), detail: cashflow.incomeMinor > 0 ? `${percent(cashflow.savingsMinor, cashflow.incomeMinor).toFixed(1)}% of income left after spending` : 'Add income to see your savings rate' }]}/>
    <div className="fin-filters"><label className="fin-search"><Search size={19}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search a name or category…" aria-label="Search transactions"/></label><select value={accountFilter} onChange={e => setAccountFilter(e.target.value)} aria-label="Filter by account"><option value="all">All accounts</option>{state.accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select><select value={categoryFilter} onChange={e => setCategoryFilter(e.target.value)} aria-label="Filter by category"><option value="all">All categories</option>{[...new Set(state.transactions.map(t => t.category))].sort().map(c => <option key={c}>{c}</option>)}</select><input type="month" value={month} onChange={e => { if (e.target.value) { onMonth(e.target.value); setAllMonths(false); } }} aria-label="Activity month"/></div>
    <div className="fin-between" style={{ flexWrap: 'wrap' }}><div className="fin-chip-tabs" role="group" aria-label="Entry type">{[['all', 'All activity'], ['income', 'Money in'], ['expense', 'Money out'], ['transfer', 'Transfers']].map(([value, label]) => <button key={value} type="button" aria-pressed={typeFilter === value} onClick={() => setTypeFilter(value)}>{label}</button>)}</div><div className="fin-row"><button className="fin-link" onClick={() => setAllMonths(!allMonths)}>{allMonths ? 'Show selected month' : 'Show all dates'}</button><Button variant="secondary" onClick={() => edit({ kind: 'transfer' })} disabled={state.accounts.length < 2}><ArrowLeftRight size={17}/>Transfer</Button></div></div>
    <section className="fin-card fin-table-card"><SectionHead title="Your activity" action={<Badge tone="neutral">{allMonths ? 'All recorded dates' : monthLabel(month)}</Badge>}/><TransactionTable rows={rows} edit={edit}/><div className="fin-table-foot"><span>{rows.length} {rows.length === 1 ? 'entry' : 'entries'} match this view</span><span>INR · {mode === 'demo' ? 'Fictional sample data' : 'Manual records'}</span></div></section>
    {!state.accounts.length && <EmptyState title="An account gives each entry a home." description="Create an account first, then record income, spending, or a transfer." action={<Button onClick={() => edit({ kind: 'account' })}>Add account<ArrowRight size={17}/></Button>}/>}
  </>;
}

function Budgets({ edit, month, onMonth }: { edit: Edit; month: string; onMonth: (month: string) => void }) {
  const { state, money } = useFinance();
  const budgets = state.budgets.filter(b => b.month === month);
  const spending = categorySpending(state, month);
  const cashflow = monthlyCashflow(state, month);
  const planned = budgets.reduce((sum, b) => sum + b.limitMinor, 0);
  const inBudget = budgets.reduce((sum, b) => sum + (spending[b.category] ?? 0), 0);
  const unbudgeted = Math.max(0, cashflow.expenseMinor - inBudget);
  const remaining = planned - inBudget;
  return <><PageHeader eyebrow="Your spending plan" title="Room for what matters." description="Give your month a direction, with space to be human." action={<Button onClick={() => edit({ kind: 'budget', month })}><Plus size={18}/>Add budget</Button>}/>
    <div className="fin-between"><SourceNote/><label className="fin-month-label"><CalendarDays size={18}/><input type="month" value={month} onChange={e => e.target.value && onMonth(e.target.value)} aria-label="Budget month"/></label></div>
    <MetricRow items={[{ label: 'Planned this month', value: money(planned), detail: `${budgets.length} budgeted categories` }, { label: 'Spent in budgeted categories', value: money(inBudget), detail: `${money(unbudgeted)} spent outside these categories` }, { label: remaining >= 0 ? 'Still in your plan' : 'Above your plan', value: money(Math.abs(remaining)), detail: planned > 0 ? `${percent(inBudget, planned).toFixed(1)}% of category budgets used` : 'Add a category to begin your plan' }]}/>
    {budgets.length ? <div className="fin-grid fin-main-grid"><section className="fin-card" style={{ padding: 0 }}>{budgets.map(budget => { const spent = spending[budget.category] ?? 0; const pct = percent(spent, budget.limitMinor); return <div className="fin-budget-row" key={budget.id}><div className="fin-icon-tile"><CategoryIcon category={budget.category}/></div><div><div className="fin-between"><h3>{budget.category}</h3><span className="fin-budget-amount">{money(spent)} <span>/ {money(budget.limitMinor)}</span></span></div><Progress value={pct} tone={pct >= 90 ? 'coral' : 'forest'} label={`${budget.category} budget used`}/><div className="fin-budget-sub"><span>{pct.toFixed(0)}% of your plan</span><span>{money(Math.abs(budget.limitMinor - spent))} {spent > budget.limitMinor ? 'over' : 'left'}</span></div></div><button className="fin-icon-button" onClick={() => edit({ kind: 'budget', entity: budget })} aria-label={`Edit ${budget.category} budget`}><Pencil size={18}/></button></div>; })}</section><div className="fin-stack"><section className="fin-card fin-editorial-card"><div className="fin-kicker">A plan, with breathing room</div><h2>Your money has a rhythm.<br/>Find yours.</h2><p>A budget helps you choose where your money goes. Adjust a category when your priorities change, and keep the essentials in view.</p><div className="fin-tip"><Sparkles size={22}/><div><h3>{unbudgeted > 0 ? 'Some spending needs a place.' : 'A little intention goes a long way.'}</h3><p>{unbudgeted > 0 ? `${money(unbudgeted)} of this month’s spending has no matching category budget. Add a budget to include it in your plan.` : 'Your spending is derived from the entries you record. Transfers are excluded so moving money does not use up a budget.'}</p></div></div></section><section className="fin-card"><SectionHead title="Your monthly picture"/><div className="fin-breakdown"><div><span>Recorded income</span><strong>{money(cashflow.incomeMinor)}</strong></div><div><span>All recorded spending</span><strong>{money(cashflow.expenseMinor)}</strong></div><div><span>Category budget total</span><strong>{money(planned)}</strong></div></div><div className="fin-footnote">Limits are plans, not transactions. Editing a budget does not move money or change your spending history.</div></section></div></div> : <EmptyState title="A little direction for your month." description="Choose a spending category and an amount that feels realistic. Recorded spending will appear automatically." action={<Button onClick={() => edit({ kind: 'budget', month })}>Create your first budget<Plus size={17}/></Button>}/>}
  </>;
}

function Portfolio({ edit }: { edit: Edit }) {
  const { state, money, mode } = useFinance();
  const [selected, setSelected] = useState<Holding | null>(null);
  const total = portfolioValue(state);
  const cost = state.holdings.reduce((sum, h) => sum + holdingCost(h), 0);
  const gain = total - cost;
  const comparisons = state.holdings.map(h => ({ name: h.symbol, cost: holdingCost(h), value: holdingValue(h) }));
  const exportHoldings = () => downloadCsv('wealthwise-holdings.csv', ['Name', 'Symbol', 'Asset class', 'Units', 'Average unit cost INR', 'Unit valuation INR', 'Valuation date', 'Cost INR', 'Value INR', 'Source'], state.holdings.map(h => [h.name, h.symbol, h.assetClass, h.quantity, h.averageCostMinor / 100, h.priceMinor / 100, h.asOf, holdingCost(h) / 100, holdingValue(h) / 100, mode === 'demo' ? 'Fictional sample' : 'Manual valuation']));
  return <><PageHeader eyebrow="Your money at work" title="A thoughtful mix." description="Understand what you own, what it cost, and how the pieces fit together." action={<div className="fin-row"><Button variant="secondary" onClick={exportHoldings} disabled={!state.holdings.length}><Download size={18}/>Export</Button><Button onClick={() => edit({ kind: 'holding' })}><Plus size={18}/>Add holding</Button></div>}/>
    <MetricRow items={[{ label: 'Current portfolio value', value: money(total), detail: `${state.holdings.length} holdings at recorded valuation prices` }, { label: 'Amount invested', value: money(cost), detail: 'Units held × average purchase cost' }, { label: 'Unrealized gain / loss', value: `${gain < 0 ? '−' : '+'}${money(Math.abs(gain))}`, detail: cost > 0 ? `${(gain / cost * 100).toFixed(2)}% return on recorded cost; not annualized` : 'Add purchase costs to calculate return' }]}/>
    {state.holdings.length ? <><div className="fin-grid fin-main-grid"><section className="fin-card"><SectionHead title="Value, with context" description="Recorded value compared with purchase cost, holding by holding."/><div className="fin-chart" role="img" aria-label="Purchase cost and current recorded value by holding"><ResponsiveContainer width="100%" height="100%"><BarChart data={comparisons} margin={{ left: 0, right: 0, top: 10, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e5eadb"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#758766', fontSize: 14 }}/><YAxis hide/><Tooltip cursor={{ fill: '#eff3e5' }} formatter={v => money(Number(v))}/><Bar dataKey="cost" name="Purchase cost" fill="#c3d3a4" radius={[4, 4, 0, 0]} maxBarSize={26} isAnimationActive={false}/><Bar dataKey="value" name="Recorded value" fill="#284c3c" radius={[4, 4, 0, 0]} maxBarSize={26} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><div className="fin-chart-summary"><span className="fin-row"><i className="fin-dot" style={{ background: '#c3d3a4' }}/>Purchase cost<i className="fin-dot" style={{ background: '#284c3c', marginLeft: 10 }}/>Recorded value</span></div><div className="fin-footnote">No historical returns are invented. This chart uses the same current quantities, costs, and dated prices shown in the holdings table.</div></section><AllocationCard/></div>
      <section className="fin-card fin-table-card"><SectionHead title="What you hold" action={<Badge tone="neutral">{mode === 'demo' ? 'Fictional sample investments' : 'Manual valuations'}</Badge>}/><div className="fin-table-wrap" tabIndex={0} role="region" aria-label="Investment records"><table className="fin-table"><thead><tr><th>Holding</th><th className="right fin-hide-mobile">Units</th><th className="right fin-hide-mobile">Cost</th><th className="right">Value</th><th className="right">Return</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{state.holdings.map(h => { const value = holdingValue(h), purchase = holdingCost(h), change = value - purchase; return <tr key={h.id}><td><button className="fin-table-name" style={{ border: 0, background: 'transparent', padding: 0, textAlign: 'left', cursor: 'pointer' }} onClick={() => setSelected(h)}><span className="fin-symbol">{h.symbol.slice(0, 3)}</span><span><strong>{h.name}</strong><small>{h.assetClass} · {dateLabel(h.asOf)}</small></span></button></td><td className="right fin-hide-mobile">{shortNumber(h.quantity)}</td><td className="right fin-hide-mobile">{money(purchase)}</td><td className="right amount">{money(value)}</td><td className={`right ${change < 0 ? 'negative' : 'fin-positive'}`}><strong>{purchase > 0 ? `${(change / purchase * 100).toFixed(2)}%` : '—'}</strong><div className="fin-ledger-sub">{change < 0 ? '−' : '+'}{money(Math.abs(change))}</div></td><td><button className="fin-icon-button" onClick={() => edit({ kind: 'holding', entity: h })} aria-label={`Edit ${h.name}`}><Pencil size={17}/></button></td></tr>; })}</tbody></table></div><div className="fin-table-foot"><span>Simple unrealized return; fees, taxes, and dividends excluded.</span><span>INR · No live prices</span></div></section></> : <EmptyState title="Start with an investment you understand." description="Record a name, units held, purchase cost, and dated valuation. No trade is placed when you add a holding." action={<Button onClick={() => edit({ kind: 'holding' })}><Plus size={18}/>Add your first holding</Button>}/>}
    <div className="fin-notice info"><Info size={22}/><p><strong>Know where a number comes from.</strong><br/>Prices are {mode === 'demo' ? 'fictional fixtures' : 'entered manually'}, not fetched from an exchange. Updating a valuation changes net worth. Real market data connections are not active.</p><TextLink view="markets">Explore the catalog</TextLink></div>
    <Dialog open={Boolean(selected)} onOpenChange={open => !open && setSelected(null)} title={selected?.name ?? 'Holding detail'} description="A clear record of what you own.">{selected && <div className="finance-dialog"><div className="fin-detail-list"><div><span>Symbol & asset class</span><strong>{selected.symbol} · {selected.assetClass}</strong></div><div><span>Units held</span><strong>{shortNumber(selected.quantity)}</strong></div><div><span>Average purchase cost / unit</span><strong>{money(selected.averageCostMinor)}</strong></div><div><span>Last recorded price / unit</span><strong>{money(selected.priceMinor)}</strong></div><div><span>Valuation date</span><strong>{dateLabel(selected.asOf, true)}</strong></div><div><span>Total recorded value</span><strong>{money(holdingValue(selected))}</strong></div></div><p className="fin-dialog-copy">Value equals units × recorded unit price. A manual holding entry does not create an order or reduce a cash account. Record the corresponding cash movement separately if appropriate.</p><div className="fin-form-actions"><Button variant="secondary" onClick={() => setSelected(null)}>Done</Button><Button onClick={() => { const holding = selected; setSelected(null); edit({ kind: 'holding', entity: holding }); }}><Pencil size={17}/>Edit holding</Button></div></div>}</Dialog>
  </>;
}

function Markets() {
  const { state, mode, dispatch, pending, href } = useFinance();
  const [tab, setTab] = useState('all');
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<CatalogInstrument | null>(null);
  const [failure, setFailure] = useState('');
  const filtered = instruments.filter(i => (tab === 'all' || (tab === 'stocks' ? i.category === 'Equity' : tab === 'funds' ? i.category !== 'Equity' : state.watchlist.includes(i.symbol))) && `${i.name} ${i.symbol} ${i.category}`.toLowerCase().includes(search.toLowerCase()));
  async function toggle(symbol: string) { setFailure(''); try { await dispatch({ type: 'toggle-watchlist', symbol }); } catch (error) { setFailure(error instanceof Error ? error.message : 'Your watchlist could not be updated.'); } }
  return <><PageHeader eyebrow="Explore the landscape" title="Curiosity, with context." description="Understand what you are looking at before deciding what to do." action={<Link className="fin-link" href={href('simulator')}>Try virtual investing<ArrowRight size={18}/></Link>}/>
    <div className="fin-notice"><Info size={22}/><p><strong>Fictional research catalog.</strong> All companies, funds, prices, and movements shown here are synthetic examples. No financial market API is connected, and no item is an investment recommendation.</p></div>
    <div className="fin-grid fin-grid-3 fin-market-grid">{instruments.slice(0, 3).map(i => <section className="fin-card fin-market-card" key={i.symbol}><div className="fin-between"><Badge tone="neutral">SAMPLE · {i.symbol}</Badge><button className="fin-icon-button" aria-label={`${state.watchlist.includes(i.symbol) ? 'Remove' : 'Add'} ${i.name} ${state.watchlist.includes(i.symbol) ? 'from' : 'to'} watchlist`} onClick={() => toggle(i.symbol)} disabled={pending}><Star size={20} fill={state.watchlist.includes(i.symbol) ? '#a9bf78' : 'none'}/></button></div><h2>{i.name}</h2><p>{i.category} · Synthetic price</p><div className="fin-between"><div className="fin-market-value">{formatMoney(i.priceMinor)}</div><Badge tone={i.changePercent >= 0 ? 'green' : 'coral'}>{i.changePercent >= 0 ? '+' : ''}{i.changePercent.toFixed(2)}%</Badge></div><button className="fin-link" onClick={() => setSelected(i)}>Understand this example<ArrowRight size={17}/></button></section>)}</div>
    <div className="fin-filters"><div className="fin-chip-tabs" role="group" aria-label="Research catalog filter">{[['all', 'All ideas'], ['stocks', 'Stocks'], ['funds', 'Funds & ETFs'], ['watchlist', `Watchlist (${state.watchlist.length})`]].map(([value, label]) => <button key={value} type="button" aria-pressed={tab === value} onClick={() => setTab(value)}>{label}</button>)}</div><label className="fin-search"><Search size={19}/><input value={search} onChange={e => setSearch(e.target.value)} aria-label="Search sample investments" placeholder="Find a sample company or fund…"/></label></div>
    {failure && <div className="fin-form-error" role="alert">{failure}</div>}
    <section className="fin-card fin-table-card"><SectionHead title={tab === 'watchlist' ? 'A watchlist with intention' : 'Make the essentials understandable'} description="A few useful questions: what does it hold, what could it cost, and what could go wrong?"/><div className="fin-table-wrap" tabIndex={0} role="region" aria-label="Investment records"><table className="fin-table"><thead><tr><th>Sample investment</th><th className="fin-hide-mobile">Risk label</th><th className="right fin-hide-mobile">Expense ratio</th><th className="right">Sample price</th><th className="right">Daily move*</th><th><span className="sr-only">Watchlist and details</span></th></tr></thead><tbody>{filtered.map(i => <tr key={i.symbol}><td><button className="fin-table-name" style={{ border: 0, background: 'transparent', padding: 0, textAlign: 'left', cursor: 'pointer' }} onClick={() => setSelected(i)}><span className="fin-symbol">{i.symbol.slice(0, 3)}</span><span><strong>{i.name}</strong><small>{i.symbol} · {i.category}</small></span></button></td><td className="fin-hide-mobile">{i.risk}</td><td className="right fin-hide-mobile">{'expenseRatio' in i ? `${i.expenseRatio}%` : '—'}</td><td className="right amount">{formatMoney(i.priceMinor)}</td><td className={`right ${i.changePercent < 0 ? 'negative' : 'fin-positive'}`}>{i.changePercent >= 0 ? '+' : ''}{i.changePercent.toFixed(2)}%</td><td><div className="fin-row-actions"><button className="fin-icon-button" onClick={() => toggle(i.symbol)} disabled={pending} aria-label={`${state.watchlist.includes(i.symbol) ? 'Remove' : 'Add'} ${i.name} ${state.watchlist.includes(i.symbol) ? 'from' : 'to'} watchlist`}><Star size={18} fill={state.watchlist.includes(i.symbol) ? '#a9bf78' : 'none'}/></button><button className="fin-icon-button" onClick={() => setSelected(i)} aria-label={`View ${i.name} research`}><ArrowRight size={18}/></button></div></td></tr>)}</tbody></table></div>{!filtered.length && <div className="fin-empty-inline">{tab === 'watchlist' ? 'Save an idea with the star button to give it a place in your watchlist.' : 'No sample investments match. Try another name or filter.'}</div>}<div className="fin-table-foot"><span>*Synthetic movements for this sample catalog.</span><span>No live prices or actual securities</span></div></section>
    <section className="fin-card fin-editorial-card"><div className="fin-between" style={{ alignItems: 'flex-start', flexWrap: 'wrap' }}><div><div className="fin-kicker">A wiser starting point</div><h2>A good question is worth<br/>more than a hot tip.</h2></div><TextLink view="learn">Build your investing foundations</TextLink></div><p style={{ maxWidth: 720 }}>Consider costs, concentration, liquidity, and time horizon. A real research page needs current source documents and verified provider data. This catalog offers a place to understand the interface while those connections remain unavailable.</p></section>
    <Dialog open={Boolean(selected)} onOpenChange={open => !open && setSelected(null)} title={selected?.name ?? 'Sample research'} description="An educational example. Not a real security or scheme.">{selected && <div className="finance-dialog fin-market-detail"><div className="fin-notice info"><Info size={20}/><p>Every metric is fictional. {mode === 'demo' ? 'Watchlist changes are saved to this demo in your browser.' : 'Your saved watchlist is personal; the research catalog remains synthetic.'}</p></div><div className="fin-detail-list" style={{ marginTop: 22 }}><div><span>Sample category</span><strong>{selected.category}</strong></div><div><span>Synthetic price</span><strong>{formatMoney(selected.priceMinor)}</strong></div><div><span>Illustrative risk label</span><strong>{selected.risk}</strong></div>{'expenseRatio' in selected && <div><span>Example expense ratio</span><strong>{selected.expenseRatio}%</strong></div>}<div><span>Source availability</span><strong>Fixture catalog · no market feed</strong></div></div><h3>Questions worth asking</h3><div className="fin-dialog-copy"><p>What are the underlying assets or business? How concentrated is the exposure? What costs, liquidity limits, and downside risks apply? Does the time horizon fit your plan?</p><p>Real price history, official fund documents, and performance comparisons will require a verified financial data provider. This interface does not invent those sources.</p></div><div className="fin-form-actions"><Button variant="secondary" onClick={() => toggle(selected.symbol)} disabled={pending}><Star size={17}/>{state.watchlist.includes(selected.symbol) ? 'Remove from watchlist' : 'Save to watchlist'}</Button><Button onClick={() => setSelected(null)}>Done</Button></div>{failure && <div className="fin-form-error" role="alert">{failure}</div>}</div>}</Dialog>
  </>;
}

function Goals({ edit }: { edit: Edit }) {
  const { state, money, href, mode } = useFinance();
  const earmarked = state.goals.reduce((sum, goal) => sum + goal.savedMinor, 0);
  const trackedGoalAssets = Math.max(0, portfolioValue(state) + state.accounts.filter(a => a.type !== 'retirement').reduce((sum, a) => sum + accountBalance(state, a.id), 0));
  const monthlyPlan = state.goals.reduce((sum, goal) => sum + goal.monthlyMinor, 0);
  const reviewMonth = mode === 'demo' ? '2026-09' : currentMonth();
  const recordedFlow = monthlyCashflow(state, reviewMonth);
  const [selected, setSelected] = useState<Goal | null>(null);
  const today = financeToday();
  return <><PageHeader eyebrow="Your life, in the making" title="Make room for someday." description="Name the things worth saving for. Give them a little momentum." action={<Button onClick={() => edit({ kind: 'goal' })}><Plus size={18}/>Create a goal</Button>}/>
    <div className="fin-notice"><Leaf size={22}/><p><strong>{money(earmarked)} earmarked for your goals.</strong> This is a planning view of assets you already own. Goal savings do not add to net worth or create bank transfers.</p></div>
    <>{earmarked > trackedGoalAssets && <div className="fin-notice info"><CircleHelp size={22}/><p><strong>A little check on your earmarks.</strong> Your goals earmark {money(earmarked)}, while recorded cash, savings, and investments total {money(trackedGoalAssets)}. Review overlapping earmarks or missing records. Retirement accounts are excluded from this comparison; no money is transferred.</p></div>}{recordedFlow.incomeMinor > 0 && monthlyPlan > Math.max(0, recordedFlow.savingsMinor) && <div className="fin-notice info"><Info size={22}/><p><strong>Your monthly plans may need more room.</strong> Goals plan for {money(monthlyPlan)} per month, compared with {money(Math.max(0, recordedFlow.savingsMinor))} left after recorded spending in {monthLabel(reviewMonth)}. This is a check against incomplete manual records, not a forecast.</p></div>}</>
    <div className="fin-grid fin-grid-3 fin-goal-grid">{state.goals.map((goal, i) => { const completed = goal.savedMinor >= goal.targetMinor; const overdue = goal.targetDate < today && !completed; return <section className="fin-card fin-goal-card" key={goal.id}><div className="fin-card-head"><div className={`fin-icon-tile ${goal.color === 'coral' ? 'coral' : ''}`}>{completed ? <CheckCheck size={23}/> : i % 3 === 0 ? <Home size={23}/> : i % 3 === 1 ? <Plane size={23}/> : <ShieldCheck size={23}/>}</div><div className="fin-row"><Badge tone={completed ? 'green' : overdue ? 'coral' : 'neutral'}>{completed ? 'Target reached' : overdue ? 'Review your date' : 'In progress'}</Badge><button className="fin-icon-button" onClick={() => edit({ kind: 'goal', entity: goal })} aria-label={`Edit ${goal.name}`}><Pencil size={17}/></button></div></div><h2>{goal.name}</h2><p className="fin-muted">A little intention for your next chapter.</p><div className="fin-goal-value">{money(goal.savedMinor)} <span>/ {money(goal.targetMinor)}</span></div><Progress value={percent(goal.savedMinor, goal.targetMinor)} tone={goal.color} label={`${goal.name} savings progress`}/><div className="fin-goal-meta"><span>{percent(goal.savedMinor, goal.targetMinor).toFixed(1)}% of the way</span><span>{dateLabel(goal.targetDate)}</span></div><div className="fin-goal-contribution"><span>Monthly plan</span><strong>{money(goal.monthlyMinor)}</strong></div><Button variant="secondary" onClick={() => setSelected(goal)} style={{ width: '100%' }}>Explore your plan<ArrowRight size={17}/></Button></section>; })}<section className="fin-card fin-goal-add"><div className="fin-icon-tile"><Plus size={25}/></div><h3>What is your next chapter?</h3><p>The big ideas. The little joys. Make a little space for them.</p><Button variant="secondary" onClick={() => edit({ kind: 'goal' })}>Give it a goal<ArrowRight size={17}/></Button></section></div>
    <Dialog open={Boolean(selected)} onOpenChange={open => !open && setSelected(null)} title={selected?.name ?? 'Your goal'} description="A useful direction, with room for life to change.">{selected && <div className="finance-dialog"><div className="fin-detail-list"><div><span>Target amount</span><strong>{money(selected.targetMinor)}</strong></div><div><span>Already earmarked</span><strong>{money(selected.savedMinor)}</strong></div><div><span>Still to plan for</span><strong>{money(Math.max(0, selected.targetMinor - selected.savedMinor))}</strong></div><div><span>Monthly contribution plan</span><strong>{money(selected.monthlyMinor)}</strong></div><div><span>Time at this monthly pace</span><strong>{selected.savedMinor >= selected.targetMinor ? 'Target reached' : selected.monthlyMinor > 0 ? `${Math.ceil((selected.targetMinor - selected.savedMinor) / selected.monthlyMinor)} months` : 'Add a monthly plan'}</strong></div><div><span>Your chosen date</span><strong>{dateLabel(selected.targetDate, true)}</strong></div></div><p className="fin-dialog-copy">This simple planning estimate divides the remaining amount by the monthly contribution, rounded up. It assumes no investment growth, inflation, or withdrawals. Contributions are plans; money does not move automatically.</p><div className="fin-form-actions"><Link className="fin-link" href={href('tools')} onClick={() => setSelected(null)}>Explore growth assumptions<ArrowRight size={17}/></Link><Button onClick={() => { const goal = selected; setSelected(null); edit({ kind: 'goal', entity: goal }); }}><Pencil size={17}/>Edit plan</Button></div></div>}</Dialog>
  </>;
}

function DebtView({ edit }: { edit: Edit }) {
  const { state, money, href } = useFinance();
  const [selected, setSelected] = useState<Debt | null>(null);
  const total = state.debts.reduce((sum, debt) => sum + debt.balanceMinor, 0);
  const estimated = state.debts.map(debt => ({ debt, ...calculateEMI(debt.balanceMinor, debt.annualRate, debt.remainingMonths) }));
  const monthly = estimated.reduce((sum, estimate) => sum + estimate.monthlyMinor, 0);
  const interest = estimated.reduce((sum, estimate) => sum + estimate.interestMinor, 0);
  const selectedEstimate = selected ? calculateEMI(selected.balanceMinor, selected.annualRate, selected.remainingMonths) : null;
  return <><PageHeader eyebrow="The other side of the picture" title="A clearer way forward." description="Understand what you owe, what it could cost, and what comes next." action={<Button onClick={() => edit({ kind: 'debt' })}><Plus size={18}/>Add loan</Button>}/>
    <MetricRow items={[{ label: 'Total outstanding', value: money(total), detail: `${state.debts.length} manually tracked ${state.debts.length === 1 ? 'loan' : 'loans'}` }, { label: 'Estimated monthly payments', value: money(monthly), detail: 'Fixed-rate reducing-balance estimates' }, { label: 'Estimated interest remaining', value: money(interest), detail: 'Excludes fees, prepayments, and rate changes' }]}/>
    {state.debts.length ? <div className="fin-grid fin-main-grid"><div className="fin-stack">{estimated.map(({ debt, monthlyMinor, totalMinor, interestMinor }) => <section className="fin-card" key={debt.id}><SectionHead title={debt.name} action={<div className="fin-row"><Badge tone="neutral">{debt.annualRate}% p.a.</Badge><button className="fin-icon-button" onClick={() => edit({ kind: 'debt', entity: debt })} aria-label={`Edit ${debt.name}`}><Pencil size={18}/></button></div>}/><div className="fin-between" style={{ alignItems: 'flex-start', flexWrap: 'wrap' }}><div><div className="fin-kicker">Outstanding principal</div><div className="fin-goal-value" style={{ marginTop: 12 }}>{money(debt.balanceMinor)}</div></div><div><div className="fin-kicker">Estimated monthly EMI</div><div className="fin-goal-value" style={{ marginTop: 12 }}>{money(monthlyMinor)}</div></div></div><div className="fin-progress" style={{ height: 13, marginTop: 15 }} role="img" aria-label={`Principal ${money(debt.balanceMinor)}, estimated interest ${money(interestMinor)}`}><span style={{ width: `${percent(debt.balanceMinor, totalMinor)}%` }}/></div><div className="fin-chart-summary"><span className="fin-row"><i className="fin-dot" style={{ background: '#284c3c' }}/>Principal<i className="fin-dot" style={{ background: '#e9eedf', border: '1px solid #cdd8ba', marginLeft: 10 }}/>Interest</span><span>{debt.remainingMonths} monthly payments</span></div><div className="fin-footnote"><div className="fin-between"><span>Estimated total future payments</span><strong style={{ fontSize: 18, color: '#183b32' }}>{money(totalMinor)}</strong></div></div><button className="fin-link" style={{ marginTop: 13 }} onClick={() => setSelected(debt)}>Understand this estimate<ArrowRight size={17}/></button></section>)}</div><section className="fin-card fin-editorial-card" style={{ alignSelf: 'start' }}><div className="fin-kicker">A useful next question</div><h2>What would a<br/>different term change?</h2><p>A shorter repayment period can reduce total interest, while increasing monthly commitments. Explore both sides before changing a plan.</p><div className="fin-tip"><Info size={22}/><div><h3>Keep the whole picture in view.</h3><p>Consider essential spending, emergency savings, and any prepayment charges. Estimates cannot replace your lender’s actual schedule.</p></div></div><Link className="fin-link" style={{ marginTop: 23 }} href={`${href('tools')}?kind=emi`}>Explore EMI scenarios<ArrowRight size={17}/></Link></section></div> : <EmptyState title="Nothing to repay here yet." description="If you have a loan, record its outstanding balance, annual rate, and remaining months to see an estimated repayment picture." action={<Button onClick={() => edit({ kind: 'debt' })}><Plus size={18}/>Add a loan</Button>}/>}
    <div className="fin-notice info"><Info size={22}/><p>Recording a loan changes the liabilities in your net worth. Estimated EMI payments are not automatically recorded as transactions. Update outstanding principal from your lender’s statement.</p></div>
    <Dialog open={Boolean(selected)} onOpenChange={open => !open && setSelected(null)} title={selected?.name ?? 'Repayment estimate'} description="An estimate with the assumptions in view.">{selected && selectedEstimate && <div className="finance-dialog"><div className="fin-detail-list"><div><span>Outstanding principal</span><strong>{money(selected.balanceMinor)}</strong></div><div><span>Annual interest rate</span><strong>{selected.annualRate}% fixed</strong></div><div><span>Remaining monthly payments</span><strong>{selected.remainingMonths}</strong></div><div><span>Estimated monthly EMI</span><strong>{money(selectedEstimate.monthlyMinor)}</strong></div><div><span>Estimated interest remaining</span><strong>{money(selectedEstimate.interestMinor)}</strong></div><div><span>Estimated total payments</span><strong>{money(selectedEstimate.totalMinor)}</strong></div></div><div className="fin-dialog-copy"><p>The calculation uses a fixed annual rate divided by 12, equal monthly payments, and a reducing principal balance. With a 0% rate, principal is divided equally across the term.</p><p>Fees, insurance, rate changes, and prepayments are excluded. The final installment may differ slightly because of rounding; your lender’s schedule is authoritative.</p></div><div className="fin-form-actions"><Button variant="secondary" onClick={() => setSelected(null)}>Done</Button><Button onClick={() => { const debt = selected; setSelected(null); edit({ kind: 'debt', entity: debt }); }}>Edit loan<Pencil size={17}/></Button></div></div>}</Dialog>
  </>;
}

export function FinanceView({ view }: { view: string }) {
  const { ready, mode } = useWorkspace();
  const [editor, setEditor] = useState<EditorState | null>(null);
  const [month, setMonth] = useState(mode === 'demo' ? '2026-09' : currentMonth());
  const normalized = view === 'money' ? 'accounts' : view === 'activity' ? 'transactions' : view === 'invest' ? 'portfolio' : view === 'plan' ? 'goals' : view === 'borrowing' ? 'debt' : view;
  const content = !ready ? <div className="fin-loading" role="status"><Leaf size={22}/>Bringing your picture together…</div> : normalized === 'accounts' ? <Accounts edit={setEditor}/> : normalized === 'transactions' ? <Transactions edit={setEditor} month={month} onMonth={setMonth}/> : normalized === 'budgets' ? <Budgets edit={setEditor} month={month} onMonth={setMonth}/> : normalized === 'portfolio' ? <Portfolio edit={setEditor}/> : normalized === 'markets' || normalized === 'watchlist' ? <Markets/> : normalized === 'goals' ? <Goals edit={setEditor}/> : normalized === 'debt' ? <DebtView edit={setEditor}/> : <Overview edit={setEditor} month={month} onMonth={setMonth}/>;
  return <div className="finance-view">{content}{editor && <FinanceEditor key={`${editor.kind}-${'entity' in editor ? editor.entity?.id ?? 'new' : 'new'}`} editor={editor} onClose={() => setEditor(null)}/>}</div>;
}
