'use client';

import Link from 'next/link';
import { useEffect, useRef, useState, type ChangeEvent, type FormEvent } from 'react';
import { ArrowDownToLine, ArrowRight, Check, CircleHelp, Database, Eye, FileSpreadsheet, LogOut, Plug, RotateCcw, ShieldCheck, Upload } from 'lucide-react';
import { categories, preferencesSchema } from '@wealthwise/contracts';
import { Badge, Button, Card, Dialog, EmptyState, Field, Input, PageHeader, formatMoney } from '@/components/ui';
import { useWorkspace } from '@/components/workspace-provider';
import { signOutAction } from '@/features/auth/actions';
import { exportTransactionsCSV, previewTransactionsCSV, type ImportPreview } from '@/lib/transactions-csv';
import './settings.css';

function download(filename: string, text: string, type: string) { const url = URL.createObjectURL(new Blob([text], { type })); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }

export function SettingsView() {
  const { state, mode, basePath, pending, ready, dispatch, resetDemo } = useWorkspace();
  const [name, setName] = useState(state.preferences.name); const [hideBalances, setHideBalances] = useState(state.preferences.hideBalances); const [monthlyReview, setMonthlyReview] = useState(state.preferences.monthlyReview);
  const [status, setStatus] = useState(''); const [error, setError] = useState(''); const [preview, setPreview] = useState<ImportPreview | null>(null); const [filename, setFilename] = useState(''); const [reading, setReading] = useState(false); const [resetOpen, setResetOpen] = useState(false); const fileInput = useRef<HTMLInputElement>(null);
  useEffect(() => { setName(state.preferences.name); setHideBalances(state.preferences.hideBalances); setMonthlyReview(state.preferences.monthlyReview); }, [state.preferences.name, state.preferences.hideBalances, state.preferences.monthlyReview]);
  async function savePreferences(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus(''); setError('');
    const parsed = preferencesSchema.safeParse({ name, hideBalances, monthlyReview, currency: 'INR' });
    if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? 'Review your preferences.'); return; }
    try { await dispatch({ type: 'save-preferences', preferences: parsed.data }); setStatus(mode === 'demo' ? 'Preferences saved in this browser’s demo.' : 'Your preferences are saved.'); } catch (problem) { setError(problem instanceof Error ? problem.message : 'Your preferences could not be saved.'); }
  }
  async function readFile(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; if (!file) return;
    setStatus(''); setError(''); setPreview(null); setFilename(file.name); setReading(true);
    try { if (file.size > 2_000_000) throw new Error('Choose a CSV smaller than 2 MB.'); const text = await file.text(); setPreview(await previewTransactionsCSV(text, state.accounts, state.transactions)); } catch (problem) { setError(problem instanceof Error ? problem.message : 'The CSV could not be read.'); } finally { setReading(false); }
  }
  async function importRows() {
    if (!preview || preview.errors.length || !preview.rows.length) return;
    setError(''); setStatus('');
    try { const count = preview.rows.length; await dispatch({ type: 'import-transactions', transactions: preview.rows }); setPreview(null); setFilename(''); if (fileInput.current) fileInput.current.value = ''; setStatus(`${count} transaction${count === 1 ? '' : 's'} imported. Your overview and budgets now include them.`); } catch (problem) { setError(problem instanceof Error ? problem.message : 'The import could not be committed. No partial batch was saved.'); }
  }
  function exportWorkspace() { download(`wealthwise-workspace-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify({ exportedAt: new Date().toISOString(), source: mode, workspace: state }, null, 2), 'application/json'); setStatus('Workspace archive downloaded. Keep it in a place you trust.'); }
  function exportActivity() { download(`wealthwise-activity-${new Date().toISOString().slice(0, 10)}.csv`, exportTransactionsCSV(state.transactions, state.accounts), 'text/csv;charset=utf-8'); setStatus('Activity CSV downloaded. Linked transfers are included for reference; they must be created with the transfer action when importing.'); }
  function template() { const account = state.accounts[0]; download('wealthwise-import-template.csv', `date,description,category,amount_inr,account_id\r\n${new Date().toISOString().slice(0, 10)},Example grocery purchase,Food,-250.00,${account?.id ?? 'REPLACE_WITH_ACCOUNT_ID'}\r\n`, 'text/csv;charset=utf-8'); }
  const dirty = name !== state.preferences.name || hideBalances !== state.preferences.hideBalances || monthlyReview !== state.preferences.monthlyReview;
  return <div className="settings-view"><PageHeader eyebrow="Your workspace" title="Make it feel like yours." description="A few considered preferences, clear data controls and a place to start fresh." />
    <div className="settings-layout"><nav className="settings-sections" aria-label="Settings sections"><a href="#settings-profile"><Eye size={18} /> Profile & preferences</a><a href="#settings-data"><Database size={18} /> Your data</a><a href="#settings-import"><Upload size={18} /> Import activity</a><a href="#settings-connections"><Plug size={18} /> Connections</a><a href="#settings-help"><CircleHelp size={18} /> Help & access</a></nav><div className="settings-content">
      <Card className="settings-card"><form onSubmit={savePreferences}><div className="settings-card-header" id="settings-profile"><div><h2>Your space, your perspective.</h2><p>{mode === 'demo' ? 'Changes apply to the sample workspace in this browser.' : 'Preferences follow your personal workspace.'}</p></div><Badge tone={mode === 'demo' ? 'green' : 'neutral'}>{mode === 'demo' ? 'DEMO' : 'PERSONAL'}</Badge></div><div className="settings-profile"><span className="settings-avatar">{name.trim().slice(0, 1).toUpperCase() || 'W'}</span><Field label="Display name"><Input autoComplete="name" value={name} onChange={event => { setName(event.target.value); setStatus(''); }} minLength={1} maxLength={80} required /></Field></div><div className="settings-row"><div><h3>Display currency</h3><p>Indian rupees, with Indian number formatting. Foreign-currency conversion is not connected.</p></div><Badge>INR · ₹</Badge></div><label className="settings-toggle-row"><div><strong>Private balance mode</strong><p>Hide large summary balances when someone is looking over your shoulder. Individual records remain available.</p></div><input type="checkbox" role="switch" checked={hideBalances} onChange={event => { setHideBalances(event.target.checked); setStatus(''); }} /><span className="settings-toggle" aria-hidden="true"><i /></span></label><label className="settings-toggle-row"><div><strong>Monthly review preference</strong><p>Remember that you want a monthly money review. Email, push notifications and scheduled delivery are not connected.</p></div><input type="checkbox" role="switch" checked={monthlyReview} onChange={event => { setMonthlyReview(event.target.checked); setStatus(''); }} /><span className="settings-toggle" aria-hidden="true"><i /></span></label><div className="settings-form-actions"><Button type="submit" disabled={!ready || pending || !dirty}>{pending ? 'Saving…' : 'Save preferences'} <Check size={18} /></Button>{dirty && <span>Unsaved changes</span>}</div></form></Card>
      {status && <div className="settings-status" role="status"><Check size={20} /><span>{status}</span></div>}{error && <div className="settings-error" role="alert">{error}</div>}
      <Card className="settings-card" ><div className="settings-card-header" id="settings-data"><div><h2>Your information, in your hands.</h2><p>Download a copy of the records in this workspace.</p></div><Database size={23} aria-hidden="true" /></div><div className="settings-data-summary"><div><strong>{state.accounts.length}</strong><span>accounts</span></div><div><strong>{state.transactions.length}</strong><span>transactions</span></div><div><strong>{state.holdings.length}</strong><span>holdings</span></div><div><strong>{state.goals.length}</strong><span>goals</span></div></div><div className="settings-export-grid"><article><FileSpreadsheet size={26} aria-hidden="true" /><h3>Activity CSV</h3><p>Transaction dates, categories, amounts and account references in a spreadsheet-friendly file.</p><Button variant="secondary" onClick={exportActivity} disabled={!ready}><ArrowDownToLine size={17} /> Export activity</Button></article><article><Database size={26} aria-hidden="true" /><h3>Workspace archive</h3><p>A JSON copy of all workspace records, including goals, settings, scenarios and learning progress.</p><Button variant="secondary" onClick={exportWorkspace} disabled={!ready}><ArrowDownToLine size={17} /> Export workspace</Button></article></div><p className="settings-fine-print">Exports contain your financial information. The JSON archive is a copy for your records; the import tool below adds transactions from CSV and does not restore a complete archive.</p></Card>
      <Card className="settings-card"><div className="settings-card-header" id="settings-import"><div><h2>Bring your activity into focus.</h2><p>Review the file before anything is added to your workspace.</p></div><Upload size={23} aria-hidden="true" /></div>{state.accounts.length ? <><div className="settings-import-instructions"><div><strong>1. Use the template.</strong><p>Dates as YYYY-MM-DD. Amounts in rupees: positive for income, negative for spending. Maximum 500 rows and 2 MB.</p></div><div><strong>2. Match your account.</strong><p>Use an account ID from the list below, or a unique account name. Add transfers with the transfer action instead.</p></div><div><strong>3. Review, then import.</strong><p>Every row must pass validation. Reimporting the same unchanged file skips records already imported.</p></div></div><Button variant="secondary" onClick={template}><ArrowDownToLine size={17} /> Download CSV template</Button><details className="settings-import-reference"><summary>Account IDs and allowed categories</summary><div className="settings-account-ids">{state.accounts.map(account => <div key={account.id}><strong>{account.name}</strong><code>{account.id}</code></div>)}</div><p><strong>Categories:</strong> {categories.filter(category => category !== 'Transfer').join(', ')}.</p></details><label className="settings-file-control"><span><Upload size={21} /> Choose a transaction CSV</span><input ref={fileInput} type="file" accept=".csv,text/csv" onChange={event => void readFile(event)} disabled={reading || pending} /><small>{reading ? 'Reading and validating your file…' : filename || 'The file is checked in your browser before confirmation.'}</small></label>
      {preview && <div className="settings-preview"><div className="settings-preview-header"><h3>Review your import.</h3><Badge tone={preview.errors.length ? 'coral' : 'green'}>{preview.errors.length ? `${preview.errors.length} row errors` : `${preview.rows.length} ready`}</Badge></div><p>{preview.totalRows} rows reviewed · {preview.skipped} already present · {preview.rows.length} new transactions.</p>{preview.errors.length > 0 && <div className="settings-validation-errors" role="alert"><strong>Fix these rows before importing.</strong><ul>{preview.errors.slice(0, 15).map(problem => <li key={`${problem.row}-${problem.message}`}><b>Row {problem.row}:</b> {problem.message}</li>)}</ul>{preview.errors.length > 15 && <p>And {preview.errors.length - 15} more errors. Correct the file and select it again.</p>}</div>}{preview.rows.length > 0 && <div className="settings-preview-scroll" role="region" aria-label="New transactions preview" tabIndex={0}><table><thead><tr><th scope="col">Date / description</th><th scope="col">Category</th><th scope="col">Amount</th></tr></thead><tbody>{preview.rows.slice(0, 8).map(transaction => <tr key={transaction.id}><td><strong>{transaction.description}</strong><span>{transaction.date}</span></td><td>{transaction.category}</td><td>{formatMoney(transaction.amountMinor)}</td></tr>)}</tbody></table></div>}{preview.rows.length > 8 && <p className="settings-fine-print">Showing the first 8 of {preview.rows.length} new transactions.</p>}<div className="settings-preview-actions"><Button disabled={pending || preview.errors.length > 0 || preview.rows.length === 0} onClick={() => void importRows()}>{pending ? 'Importing…' : `Import ${preview.rows.length} transaction${preview.rows.length === 1 ? '' : 's'}`} <ArrowRight size={18} /></Button><Button variant="ghost" onClick={() => { setPreview(null); setFilename(''); if (fileInput.current) fileInput.current.value = ''; }}>Cancel</Button></div>{!preview.rows.length && !preview.errors.length && <p className="settings-fine-print">Everything in this file is already present. No changes are needed.</p>}</div>}</> : <EmptyState title="Give your activity an account first." description="Create a cash or savings account, then return here to import its transactions." action={<Link href={`${basePath}/accounts`} className="settings-action-link">Add an account <ArrowRight size={17} /></Link>} />}</Card>
      <Card className="settings-card"><div className="settings-card-header" id="settings-connections"><div><h2>A clear boundary for connected services.</h2><p>Manual records work now. External financial APIs come later.</p></div><Plug size={23} aria-hidden="true" /></div>{[{ name: 'Bank accounts', description: 'No bank aggregation or automatic transaction sync.' }, { name: 'Market prices', description: 'Holdings use dated manual prices; the practice catalogue uses sample data.' }, { name: 'AI research', description: 'Insights explain recorded information with rules. No AI provider is connected.' }].map(connection => <div className="settings-row" key={connection.name}><div><h3>{connection.name}</h3><p>{connection.description}</p></div><Badge>Not connected</Badge></div>)}<p className="settings-fine-print">Never enter bank passwords, card security codes or brokerage credentials into a manual account form.</p></Card>
      <Card className="settings-card"><div className="settings-card-header" id="settings-help"><div><h2>A little help, when you need it.</h2><p>Understand the controls and keep access to your workspace in your hands.</p></div><ShieldCheck size={23} aria-hidden="true" /></div><div className="settings-help-links"><Link href="/help">Using WealthWise <ArrowRight size={18} /></Link><Link href="/security">Account security <ArrowRight size={18} /></Link><Link href="/privacy">How information is used <ArrowRight size={18} /></Link></div>{mode === 'demo' ? <div className="settings-session"><div><h3>A fresh look around?</h3><p>Reset only this browser’s demo records, preferences and practice orders. Your personal workspace is separate.</p></div><Button variant="secondary" onClick={() => setResetOpen(true)}><RotateCcw size={18} /> Reset demo</Button></div> : <div className="settings-session"><div><h3>Leaving this device?</h3><p>Sign out of this browser. Your saved records stay in your account.</p></div><form action={signOutAction}><Button variant="secondary" type="submit"><LogOut size={18} /> Sign out</Button></form></div>}</Card>
    </div></div><Dialog open={resetOpen} onOpenChange={setResetOpen} title="A fresh start for this demo?" description="This restores the original sample accounts, activity, goals, practice orders and preferences in this browser. Personal account records are separate."><div className="settings-reset-actions"><Button variant="secondary" onClick={() => setResetOpen(false)}>Keep exploring</Button><Button onClick={() => { if (resetDemo()) { setPreview(null); setFilename(''); if (fileInput.current) fileInput.current.value = ''; setResetOpen(false); setError(''); setStatus('Demo reset to its original sample records.'); } else { setResetOpen(false); setStatus(''); setError('The demo could not be reset because browser storage is unavailable. Allow local storage and try again.'); } }}>Reset this demo</Button></div></Dialog>
  </div>;
}
